-- 20260707_02_seed_contextual_search_clues.sql
-- Source: transcript-specific Markdown regenerated from the original JSON.
-- Matching key: videos.youtube_video_id + segments.start_seconds + segments.end_seconds.
-- Safe to rerun. It replaces only contextual_clues for the seeded intervals.

BEGIN;

WITH seed (
  youtube_video_id,
  start_seconds,
  end_seconds,
  contextual_clues
) AS (
VALUES
  ('1FN_xHL-u-Q', 360, 418, ARRAY['I''ve been playing half notes per measure which is per bow.', 'Now I''ve got that and then maybe what I should probably do is go back to the scale and show you what I''m doing with the scale and then bring it']::text[]),
  ('IJxLAyBdIM4', 42, 72, ARRAY['You hear how I''m doing a little bit of an accent after or on every downbeat of each measure?', 'This is very similar in motion, vertical motion, to that part from the Bach Partita, third Partita in E major, first movement.']::text[]),
  ('IJxLAyBdIM4', 150, 173, ARRAY['The reason why I think, in my opinion, is because when you start each downbeat and you have that accent, I''m accenting it... accenting the first note because I''m throwing the bow']::text[]),
  ('7YvI9La1T2U', 84, 129, ARRAY['That also helps because we want to have a little bit of an accent on that up bow.', 'So playing it this way with extra bow on the up bow will give you that accent.']::text[]),
  ('mjTr6fKPgBM', 136, 161, ARRAY['I think what I''ll probably end up doing is on that down bow D with the accent, I think I''m going to hold it just a little bit extra time.', 'Then on the, I think I''m going to consider that one grouping of notes, kind of a gesture to get to, and then another gesture.']::text[]),
  ('mjTr6fKPgBM', 305, 341, ARRAY['Just the accent of D down.', 'It sounds like I''m ... enunciating.']::text[]),
  ('ZNxKJcSdMsU', 75, 93, ARRAY['I''m thinking of those accents as kind of a little bit of a cough. "eh, eh, eh." And then a little bit more...', 'Just kind of sit in line there thinking.']::text[]),
  ('Qs-tFga-tVg', 150, 180, ARRAY['That very first one, I''m doing a third finger on the A string and then string crossing.', 'These next three are not, but you have to make it sound like it''s still a string crossing.']::text[]),
  ('xT8VoIllyfo', 17, 57, ARRAY['I don''t know if it''s easier if I do it this way, maybe you can see my fingers better.', 'You can remember the accents because it''s on the downbeat, on the down bows.']::text[]),
  ('NZVSQRzo48o', 10, 44, ARRAY['It''s very important that you bring up accents in an orchestra because those are the things that pop out.', 'Now if you noticed, I was really bringing out those accents.']::text[]),
  ('NZVSQRzo48o', 134, 157, ARRAY['Even on the accents, you don''t want to play too long.', 'Make sure that your notes are short enough.']::text[]),
  ('1FN_xHL-u-Q', 110, 137, ARRAY['Even when you''re not nervous I have I guess from my mom a hyperthyroid and so I don''t know if what that is but basically my metabolism is super fast.']::text[]),
  ('opNpw5mOowo', 108, 132, ARRAY['One good way to start this piece, because it''s so exposed, you''re going to be probably a little bit nervous coming in, so I would recommend first getting rid of all your carbon']::text[]),
  ('qbFqvpvo36Q', 78, 99, ARRAY['When I get up to play, probably the most nervous part of playing for me is getting my violin up and getting set ready to play.', 'I breathe down here, so my diaphragm expands and then contracts to let the air out.']::text[]),
  ('qbFqvpvo36Q', 165, 180, ARRAY['When you breathe correctly, it clears your mind, particularly the breathing out, that''s the really important thing because you could breathe in and you''re going to be nervous.']::text[]),
  ('ETEads8iW24', 101, 124, ARRAY['Because if you''re going to get a good clean sound, you''re going to need your wrist to', 'What that does for me is when I get nervous and I start to tense up here, at least...']::text[]),
  ('QJL4rdBYbts', 111, 125, ARRAY['Let''s give an example of you''re nervous, you''re on stage, you''ve got a little bit of stage right and what''s the first thing to go?', 'Now when I''m tense and I try to go for that note, you''re most likely going to miss']::text[]),
  ('QJL4rdBYbts', 132, 145, ARRAY['If then, if you think, oh, well, I''m nervous, I''m going to overshoot or I''m going to shoot a little bit higher, then you start hitting too high.']::text[]),
  ('Xq0xj4x8UgU', 0, 50, ARRAY['Let me just talk about what I know, which is at the tip of the bow, basically all I''m doing at the tip of the bow is I''m releasing any pressure in my fingers, keeping them very']::text[]),
  ('Xq0xj4x8UgU', 67, 115, ARRAY['Typically what I''ll do if I want a really smooth bow change is, first of all, I''ll tip my hair over just slightly so there''s less contact with the string.']::text[]),
  ('4Hkm2kBu_mE', 401, 460, ARRAY['When you''re playing it, when you want to give a shape as the shape is curving over this way, you need to be increasing the amount of bow you''re using, and as you hit the peak']::text[]),
  ('neMlvsSMNEI', 141, 179, ARRAY['The other trick to get that slur to come in correctly or sound correct is to not start sliding until after your bow change, so you get that effect.']::text[]),
  ('ajbxxs-4SMk', 16, 49, ARRAY['So that sounds a little bit too classical, I think, so what I need to do is I think I need to just make it more smooth so the bow changes and also really punch those grace notes']::text[]),
  ('517uzXPQ3xg', 274, 317, ARRAY['The reason why is because I want it to sound different.', 'Far, up to measure six, I''ve been playing']::text[]),
  ('EKeY_En_46g', 71, 116, ARRAY['Then you should be able to get a nice relaxed bow grip.', 'My bow hold typically from this angle ends up like this.']::text[]),
  ('UDxKpYNJUyk', 282, 313, ARRAY['That second time is quieter than the first.', 'In fact, I just barely lost my place for whatever reason.']::text[]),
  ('UDxKpYNJUyk', 468, 486, ARRAY['Or you can also think of a prism, where if you''re turning it, you''re getting different angles of light refraction.']::text[]),
  ('kk6xaUwKCwg', 86, 120, ARRAY['When you''re doing string crossings within a passage, make sure that you stop your bow just before you make the string crossing, otherwise you kind of get ahead of yourself and']::text[]),
  ('Qs-tFga-tVg', 99, 126, ARRAY['Next part, this is all about string crossing, which requires your arm to move.', 'If you try to force it with your wrist, first of all, you get a bad sound.']::text[]),
  ('MKr5VVrQIWQ', 0, 33, ARRAY['This stroke is called spiccato, and every bow has a little bit different of a bouncing point.', 'My bow, because it''s by it''s a la fleur style, which is a little bit more of a, I guess, kind of baroque']::text[]),
  ('Kobf2zvvvbk', 401, 441, ARRAY['I apologize I don''t know these notes as well as I used to when you get to here, probably because it''s a cadenza you can do whatever you want but probably I would recommend getting']::text[]),
  ('g-Df8xaScUM', 595, 642, ARRAY['I think it''s just undue stress, and I don''t think I need to do that.', 'I don''t know why that''s happening, so I''m trying to figure it out.']::text[]),
  ('Fic0zak8K5Y', 444, 468, ARRAY['I''m starting my bow very slowly and speeding it up and then bringing it back down again.', 'Coming out of this up bow in very slow motion is...']::text[]),
  ('tHVk9XfXUC4', 0, 32, ARRAY['What I''m going to talk about today is how to break a chord on Quadruple stops.', 'This is quadruple stops requested by zero star 36 and I have a video on triple stops if you''re curious and those triple stops I play just in one']::text[]),
  ('1R8WiILKtJs', 19, 67, ARRAY['Use but Let''s see if this helps at all So let''s think of a couple of passages where there are double stops for instance in the Mendelssohn ballet concerto that second page where']::text[]),
  ('1R8WiILKtJs', 65, 114, ARRAY['See this that part that goes And those are all those are all thirds as well so now, what I''m talking about Okay, they''re very hard to get in tune if If you don''t do it correctly']::text[]),
  ('1R8WiILKtJs', 261, 304, ARRAY['I can combine those two, and then I can drop out that extra note.']::text[]),
  ('1R8WiILKtJs', 374, 386, ARRAY['I''ll probably hit 90% of the notes.', 'I''m getting pretty good at it now.']::text[]),
  ('jrzuLv0ZT0w', 0, 46, ARRAY['Put it down, very relaxed, make sure that your hand is totally relaxed, and then play the two notes.', 'What I''m first going to do is shake out my hand and make sure that it''s totally relaxed.']::text[]),
  ('1QFHZfQzZ0E', 367, 381, ARRAY['What that does for the audience, it really gives them a chance to experience a whole new layer of musicality that they didn''t have when you first started.']::text[]),
  ('AvUsPxVHSiA', 348, 358, ARRAY['It''s almost like they''re directly related, where the second thought is just an extension of the first thought.', 'When you''re playing it that way, think of it in those terms, so when you come in,']::text[]),
  ('AvUsPxVHSiA', 360, 382, ARRAY['What I''m saying is, they are the same style, but it does need a little bit of that variation', 'It should also sound similar to ...']::text[]),
  ('Qa1Zj_L3x8c', 111, 158, ARRAY['Going into the double stops, make sure you keep your bow moving when you go into the double stops, and really what that involves is your bow mostly, as if you were just going']::text[]),
  ('Qa1Zj_L3x8c', 131, 174, ARRAY['Going into the double stops, make sure you keep your bow moving when you go into the double stops, and really what that involves is your bow mostly, as if you were just going to']::text[]),
  ('IL4cmuWiQUk', 0, 52, ARRAY['When you take the scale, all of those eight notes, what you''re doing is you''re going up the scale, instead of going up the scale one scale step at a time, you''re going up two']::text[]),
  ('IL4cmuWiQUk', 117, 163, ARRAY['If you do it right, you don''t have to practice it, so that particular one, I''m going to have to practice a little bit slower, so there we go, I got it.']::text[]),
  ('HVga8H4zvyQ', 0, 28, ARRAY['This is triple stops and I''m going to demonstrate by going to the Bach Fugue from the G minor Sonata.', 'The way I''m doing this is when you come down with your bow, there is a full body motion']::text[]),
  ('HVga8H4zvyQ', 91, 121, ARRAY['Either it''s going to cut your sound short or you won''t hit all three strings, and what we''re trying to do with the triple stops is hit all three strings simultaneously, and you']::text[]),
  ('KAiPJsuDM50', 260, 311, ARRAY['Then later on, you have measure 40.', 'You have those kind of fast notes.']::text[]),
  ('KAiPJsuDM50', 304, 360, ARRAY['Practice sliding up and down until you get comfortable', 'This is measure 43, shifting up to second position, back to first position.']::text[]),
  ('KAiPJsuDM50', 361, 378, ARRAY['Practice sliding up and down until you get comfortable with it.', 'When you do the open E on measure 50, as soon as you']::text[]),
  ('PTWDtHFcwIA', 73, 102, ARRAY['When you do string crossings that are that quick, the best way that I found is to actually treat it or at least start by playing it as a double stop so that it''s right along both']::text[]),
  ('9Fh25Tiq4Sc', 0, 40, ARRAY['This is my solo violin arrangement of "Song of Skyrim" and I''m a little crazy because I just wrote this about 20 minutes ago and it has a lot of fifths and fourths and anyways.']::text[]),
  ('Qs-tFga-tVg', 5, 39, ARRAY['We have some double stops that are pretty tricky, so I would recommend that you practice it kind of like this.', 'As I speed this up very slowly, which is the key, by the way, to practicing or to playing very quickly, is to practice very slowly at first and']::text[]),
  ('aICv2fgoNg0', 38, 86, ARRAY['The best way that I found is that if you take your elbow and bring it a little bit to the, let''s see, I think it''s left, I''m not exactly sure, anyways, if your hand turns in this']::text[]),
  ('aICv2fgoNg0', 129, 146, ARRAY['And probably somebody is going to accuse me and say, well, I practice, but I have long fingernails and I''m going to say, you can''t play thirds.']::text[]),
  ('aICv2fgoNg0', 172, 180, ARRAY['Be ready to have your hand turned in this way.']::text[]),
  ('aICv2fgoNg0', 307, 348, ARRAY['I think he does that because then in order to get up to third position on 55 to hit this,', 'I''m not exactly sure if these are the right notes, but at 54, I put open strings.']::text[]),
  ('aICv2fgoNg0', 407, 443, ARRAY['You have to really, really place your finger very, very well, precisely so that you avoid touching the other strings.', 'Otherwise, you''re going to lose the sound.']::text[]),
  ('ygvtjd7NNJE', 0, 36, ARRAY['Today I wanted to show you a little bit how I''m practicing double voices and so on the violin you can play two notes at the same time so let me demonstrate.']::text[]),
  ('ygvtjd7NNJE', 68, 107, ARRAY['Totally do this later once you''re you want your techniques a little bit closer to to being able to play double stops which you can do but let me show you why this is harder okay']::text[]),
  ('ygvtjd7NNJE', 137, 160, ARRAY['That sounds like a solid note let''s do a couple of these so what I''m doing there is I''m actually in the middle of the melody I''m immediately going back to the double stop again']::text[]),
  ('CvWVNMybMeQ', 270, 330, ARRAY['I''m actually in the E flat fifth and the reason why is because this first note is actually extended up into not a new position, just next to the second finger.']::text[]),
  ('CvWVNMybMeQ', 364, 406, ARRAY['When I get to this note, I''m forming the hand frame, the octave right here.', 'If I do it that way and I keep the hand frame very consistent and I know which position']::text[]),
  ('3bAWqnjPfV4', 583, 638, ARRAY['Here you want to just quickly go into half position for that one B natural on second finger, then come right back out of it.', 'In measure 37, those last four notes, the last three notes of that group should be crescendoing.']::text[]),
  ('1FN_xHL-u-Q', 46, 87, ARRAY['What I''m concentrating on here is the intonation and the consistency of sound.', 'I always shift on those D''s that one and here making sure you''re totally relaxed.']::text[]),
  ('Fic0zak8K5Y', 79, 117, ARRAY['The opening, before you come in, the orchestra has these moving triple eighth notes and quarter notes, and then, right before, you have a rest, bend.']::text[]),
  ('1R8WiILKtJs', 127, 148, ARRAY['You see what I''m doing I''m instead of having to go on If it''s out of tune what I''m doing is I''m stopping and holding that that next note To make sure I''m hitting it right so if']::text[]),
  ('jrzuLv0ZT0w', 31, 69, ARRAY['What I''m going to do when I place my finger down is figure out, ok, how am I going to get more of my finger flesh on the D string to raise that pitch.']::text[]),
  ('S-xMtLyNw1w', 250, 302, ARRAY['The other part of the motion is down here, so watch my elbow.', 'Do you see how my elbow']::text[]),
  ('S-xMtLyNw1w', 270, 321, ARRAY['If I just barely move, you can see that my finger bends about the same speed as my elbow moving, but my finger can''t move anywhere until my elbow moves first.']::text[]),
  ('MC71NLSy3Dg', 97, 147, ARRAY['One of them is that third note on the scale The E and the other note is the the B And I technically only raise it when I''m moving up the scale, but if you listen Both of those']::text[]),
  ('MC71NLSy3Dg', 283, 321, ARRAY['If you are an advanced player and you want to add a little bit to your playing, I would experiment a little bit with that in adding a little bit of extra pitch going upwards on']::text[]),
  ('MC71NLSy3Dg', 346, 361, ARRAY['Because on the second phrase now what I''m doing when I come in again a little bit raised but immediately coming out of this because it comes out minor now I''m going to drop all my']::text[]),
  ('ETEads8iW24', 60, 76, ARRAY['You''re not going to want to play this anymore if you do that too much.', 'Sorry about the pitch.']::text[]),
  ('oVU8RYnnrzg', 13, 27, ARRAY['You have a lot of mobility in your left hand to move on those really fast runs and getting your intonation good.', 'What I''d like to talk a little bit about is your, I guess, your right hand, your bow hand.']::text[]),
  ('F3DjMch3ex0', 364, 397, ARRAY['On the second part, you can think of this as another big Rambo made up of two sub-Rainbows, sub-phrases, and that first phrase, instead of just playing those notes flatly along']::text[]),
  ('eh_5PwiFJoU', 0, 37, ARRAY['This is a big disclaimer, I do not profess to have perfect intonation myself.', 'If you want perfect intonation, someone like Heifetz has pretty darn close.']::text[]),
  ('eh_5PwiFJoU', 63, 98, ARRAY['That''s a good way to tune your notes that are also your strings, and so the G, D, A and E are easy to tune because you can listen for and feel the vibrations.']::text[]),
  ('eh_5PwiFJoU', 120, 180, ARRAY['Try playing a scale very slowly, and on each note you should be feeling the vibrations And your fingers', 'If I do it slow enough, I can also feel it in my fingers.']::text[]),
  ('QJL4rdBYbts', 41, 62, ARRAY['What I used to do when I was probably a teenager, I used to go, and I have perfect pitch.', 'Let''s say I''m going from the A here to an octave above, okay?']::text[]),
  ('Kobf2zvvvbk', 25, 64, ARRAY['So make sure you get all those notes right, and in that first run, make sure you hug those notes really tightly, pitch-wise.', 'Make sure that B-flat is low, and then make sure the C-sharp is high, F is low, B-flat is low, C-sharp is high, and then F is low, and B-flat is']::text[]),
  ('DonIU4wS8tU', 16, 39, ARRAY['Particularly today as I was worshiping with my family, it was nice to just see how in tune my family is with each other and how well we get along.']::text[]),
  ('Vz3hsk-jnsk', 54, 70, ARRAY['First way. [MUSIC] Because we all know it''s very important to be able to play all of the notes in tune and in rhythm.', 'Now that I''ve got that down, let''s move to the second layer which is add a little bit of musicality. [MUSIC]']::text[]),
  ('KAiPJsuDM50', 6, 65, ARRAY['You do start in second position, make sure you get a nice octave using your hand frame so your hand is relaxed forming an octave.', 'Starting from the beginning, I''m not going to play the whole thing but I''ll just kind of jump around to where I think the most important points']::text[]),
  ('mK47Hd4X0sM', 361, 391, ARRAY['First and third all the way down.', 'I don''t have the background.']::text[]),
  ('E66s-OJI0m0', 5, 61, ARRAY['Let me just make sure I''m in tune.', 'I did try tuning it a little bit and for the last 10 minutes I''ve been getting a steady cloud of rosin coming off my bow.']::text[]),
  ('E66s-OJI0m0', 41, 73, ARRAY['Also note that if it keeps slipping out of tune that''s normal because when they package it and send it it''s going to start out with very loose strings and the bridge will not be']::text[]),
  ('E66s-OJI0m0', 81, 105, ARRAY['Make sure you get it on properly and to make sure that the sound post is still standing because it''s possible that during shipping you can fall.']::text[]),
  ('E66s-OJI0m0', 315, 360, ARRAY['You shouldn''t normally play it on the D string with me about the trick.', 'Alright, well, in the same vein. et cetera, et cetera.']::text[]),
  ('IDny7YYxobE', 177, 178, ARRAY['I guess I should explain what I''m doing.']::text[]),
  ('sNGIFa6gZqo', 0, 39, ARRAY['Let''s play "Name That Tune".']::text[]),
  ('ve2RpfbHtd4', 6, 61, ARRAY['I''m going to play it very slowly, show you my fingerings, and you can also listen to the intonation.', 'I''m going to show you how I''m going to practice "Let It Go" by Frozen, or from the Disney movie Frozen, with a metronome.']::text[]),
  ('dEVFN71MEGU', 460, 474, ARRAY['Here, you''re going to use your middle finger and go to the, first you have your open A and you also have another A on the D string, which is in third position.']::text[]),
  ('ewKUCf-ANlo', 169, 178, ARRAY['Either scratch the sound or it gets a little The sound gets distorted and also it''s possible that your intonation kit can get distorted if you push too hard']::text[]),
  ('ewKUCf-ANlo', 593, 618, ARRAY['There''s something that you can see through, okay?', 'Where the breathiness creates the illusion that there''s a ghost or something.']::text[]),
  ('517uzXPQ3xg', 106, 159, ARRAY['For example if I went from first to third position as in well let''s see first of all measure three very last note of that G when you get to this G or even the G before that you']::text[]),
  ('517uzXPQ3xg', 156, 182, ARRAY['That it''s very subtle but I''m just tapping my finger down just to make sure I can hear what what pitch it''s going to be and that gives me more reassurance as a performer that I''m']::text[]),
  ('69_-GJO5Z9M', 49, 91, ARRAY['I''m not moving my fingers, which was part of the problem that I had before, but I''m actually using my arm to pull my hand forward.', 'Which is that you can just tap your finger like this, and you can tell if you''re on the right pitch.']::text[]),
  ('69_-GJO5Z9M', 429, 484, ARRAY['Again, I''m using my arm to shift, so although I can see where I need to go, I''m also going into third position, which my arm already knows where to go.']::text[]),
  ('69_-GJO5Z9M', 1045, 1090, ARRAY['If you can write down the fingers like in your mind and go, yes, three, one, three, two, two, four.', 'E and then just popping my fourth finger down.']::text[]),
  ('wLTDCW5Rv8o', 290, 349, ARRAY['If you can see here, if you look close enough, my violin is shaking, but what I''m doing is, I''m lifting my violin up just, you see how this is kind of at a flat angle with the']::text[]),
  ('wLTDCW5Rv8o', 332, 360, ARRAY['That vibration, the shock of that vibration is being taken by this big part of my upper body here, and so it''s being dispersed, so I don''t feel it very much at all.']::text[]),
  ('ZNxKJcSdMsU', 117, 143, ARRAY['He''s thinking, "Wouldn''t it be nice if I just died right now?" And so on to the double trills.', 'Then he''s sliding back into his bed again.']::text[]),
  ('FVIJwUEphWg', 79, 118, ARRAY['The little trill things, I''m not exactly sure what they''re doing, but it''s something like either just two notes or this one might just', 'I''ll play it slowly so you can see my fingers.']::text[]),
  ('Fic0zak8K5Y', 586, 628, ARRAY['Here I am, I''m playing the solo now, and then the next phrase.', 'You''re switching between those two, technically speaking, so that your bow is doing something different than your fingers.']::text[]),
  ('opNpw5mOowo', 36, 71, ARRAY['So the orchestra comes in, just has this...', 'It''s a little blurry in here, but because I''ve played violin for so long, I can kind of tell what''s happening, so I''ll give you the inside scoop.']::text[]),
  ('opNpw5mOowo', 474, 500, ARRAY['Because that gives it more of a fat sound to me.', 'Which is initiated here from the elbow.']::text[]),
  ('4Hkm2kBu_mE', 5, 37, ARRAY['Because they start out, you feel this beat, which means then if the orchestra is continuing to do that, and they have sixteenth notes, are those sixteenth notes?']::text[]),
  ('AvUsPxVHSiA', 391, 410, ARRAY['So, putting those two together, then you get that nice opening, which, for me, Mozart concertos tend to be the most difficult when you start, so it''s that very first phrase that']::text[]),
  ('VYCyZFjBghs', 105, 124, ARRAY['Just like I have done in the past as a youtuber and if you''d like to see a youtuber a fellow youtuber like myself Who''s been here a long time actually go to Carnegie Hall for this']::text[]),
  ('NZVSQRzo48o', 62, 73, ARRAY['There''s a saying in orchestra playing that, well there''s two sayings actually.', 'One of them is that you''re like, an entire section of violins is like this row belt where everybody is chained together.']::text[]),
  ('CvWVNMybMeQ', 20, 68, ARRAY['In fact, going through college, at one point our teacher said, "You''ve got to practice," or the music program said, "You have to practice four hours every single day." And I was']::text[]),
  ('3bAWqnjPfV4', 151, 180, ARRAY['You can either extend up to a fourth finger here or you can go on the E string.', 'It''s harder so if you find difficulty with that you can just do it on the E string. ups.']::text[]),
  ('3bAWqnjPfV4', 272, 311, ARRAY['I generally like doing the fourth finger on a lot of these long notes because it sounds less harsh than the open string, but when it''s fast on a sixteenth note then I generally']::text[]),
  ('3bAWqnjPfV4', 311, 360, ARRAY['Here you want to stop your bow in between each of the eighth notes.', 'When you listen for the entrance you''ll hear the first violin go ... and then that''s you, that''s when you''re supposed to come in.']::text[]),
  ('1FN_xHL-u-Q', 0, 51, ARRAY['I''m going to do my best and see if I can at least explain how I think you should be doing scales and maybe I should amend my ways and figure out how to do or how to do yeah how to']::text[]),
  ('1FN_xHL-u-Q', 311, 351, ARRAY['Feel it in your fingers, feel it in your wrist, your arm and your elbow and your forearm over here.', 'Because if you can do a whole three octave scale and keep the tone consistent and keep it in tune and also stay relaxed here, well think about']::text[]),
  ('N7Exnp4wL8M', 0, 16, ARRAY['This piece that I''m about to play for you was requested by Scottbo68, and it was requested today, and so I haven''t had time to practice this.']::text[]),
  ('UDxKpYNJUyk', 47, 78, ARRAY['You can even do this just by extending your pinky out or letting your wrist bend a little bit like that.', 'That way, your home base, if you will, your home string is the D string, and the A string is the one that you have to cross to.']::text[]),
  ('Xq0xj4x8UgU', 103, 130, ARRAY['My pinky''s just adding just a little bit of counterbalance weight.', 'That should get rid of a lot of those unwanted sounds.']::text[]),
  ('MRtvUvg5Afs', 33, 72, ARRAY['I don''t advocate any particular type of bowgrip or anything, in fact when I''m playing, usually what I focus more on is this, arm weight and elbow section of my body, not this']::text[]),
  ('MRtvUvg5Afs', 99, 125, ARRAY['Then my pinky sometimes kind of comes off just because it''s so relaxed, I mean my fingers can just do this.', 'When you put your bow down, there is a contact point, and if you do it at the right contact point, just wherever your bow is, you should be able']::text[]),
  ('MRtvUvg5Afs', 137, 151, ARRAY['If I''m doing up a staccato for instance, where I have my first finger contacting the bow, I move it up to the second joint.', 'Sometimes with techniques, you need a different, or at least I use a different bowgrip, I don''t know if you need it, but I use a different']::text[]),
  ('MRtvUvg5Afs', 162, 180, ARRAY['It''s just a momentary technique that I usually switch back to right after the up bow staccato, but doing this, putting my finger over to the second joint, gives me more of ability']::text[]),
  ('tHVk9XfXUC4', 86, 126, ARRAY['The better Okay, now most of the arm weight that I''m applying to this chord Is right here just just maybe this much bow and then what I do is I start with with the weight And as I']::text[]),
  ('1R8WiILKtJs', 304, 335, ARRAY['You see how I''m just playing that note once?', 'I can combine those two, and then I can drop out that extra note.']::text[]),
  ('jrzuLv0ZT0w', 146, 177, ARRAY['The grooves that you get from putting your finger down will help you during practice to remember where it''s supposed to be.', 'Then during your practice, shake your hand out, get your hand up where you think it''s supposed to go.']::text[]),
  ('qbFqvpvo36Q', 103, 135, ARRAY['A good practice would be to, well, I guess walking on stage and then taking your bow and then as you''re bringing your violin up, breathe and then exhale as your bow gets into']::text[]),
  ('G3MAdfyihhw', 294, 312, ARRAY['Assume I didn''t watch their fingers, but I assume we just stay in first position this whole time through this whole piece, unless you have to go up to a higher note.']::text[]),
  ('G3MAdfyihhw', 397, 425, ARRAY['I''m not doing anything on my wrist, necessarily.', 'If you can do this, where you take your bow...']::text[]),
  ('S-xMtLyNw1w', 360, 397, ARRAY['Good vibrato, rather than try to move your hand this way, stick your finger down, just very slowly move it from a bent position, not totally square, but just at a little bit of an']::text[]),
  ('MC71NLSy3Dg', 442, 485, ARRAY['Like I said before very advanced technique and if you do have a teacher I would ask them about this first and make sure that it sounds the way that it should sound which is to']::text[]),
  ('MKr5VVrQIWQ', 152, 181, ARRAY['Watch Pearlman do this, which I just I like Pearlman in general, but what he, you can see his fingers.', 'My hand is so relaxed right now that my pinky can just come right off.']::text[]),
  ('MKr5VVrQIWQ', 252, 303, ARRAY['Another thing that helps me anyway is putting my bow hair flat against the string.']::text[]),
  ('IJxLAyBdIM4', 309, 360, ARRAY['You''re not going to really hear the bounce when you''re doing it slowly, but you should be feeling that motion so that when you do do it at normal speed, then you actually get that']::text[]),
  ('IJxLAyBdIM4', 450, 474, ARRAY['If I were to practice this myself, I would probably practice it very slowly.', 'If I kept missing it like I am right now, I''ll actually let my fingers slide up and']::text[]),
  ('l8EOOzC1xhE', 88, 123, ARRAY['I''m starting to use more of this finger here to transfer the weight from my arm into my bow.', 'It''s just that your arm weight is being transferred through typically these two fingers.']::text[]),
  ('1QFHZfQzZ0E', 425, 444, ARRAY['It''s lyrical and it''s flowing, and that''s the kind of thing that I''d like to hear personally', 'I don''t know if you can hear it on my camera because it equalizes the volume.']::text[]),
  ('1QFHZfQzZ0E', 467, 477, ARRAY['So make sure you make that distinction so it doesn''t all sound the same.', 'If it sounds different enough and it''s engaging, then I think that''ll make the difference.']::text[]),
  ('SfwD0wHKqoI', 32, 79, ARRAY['That harmonic, the easiest way that I''ve found to hit that harmonic is by keeping my third finger, instead of hitting with my fourth finger, I hit it with my third finger.']::text[]),
  ('SfwD0wHKqoI', 118, 137, ARRAY['Someone wrote down that his bowing seems so effortless, and I agree with that, and part of the reason I think that it''s so effortless is because if you look at his hand really']::text[]),
  ('SfwD0wHKqoI', 148, 180, ARRAY['There are certain areas where at the frog, for instance, you need your pinky to help counterbalance the weight so that it doesn''t scratch, and there''s also spots at, for instance']::text[]),
  ('c2GafXagxmk', 75, 98, ARRAY['Fingers completely relaxed, keep them at a good contact spot with the bow, and then rest your bow on the string, keeping in mind that it''s your arm weight that''s going to dictate']::text[]),
  ('Qa1Zj_L3x8c', 368, 397, ARRAY['For musicality, once you have the feeling of the bow and being able to use the right amount of bow in the', 'When I''m starting this up bow.']::text[]),
  ('Qa1Zj_L3x8c', 595, 607, ARRAY['You''re starting off the phrase at the beginning of the rainbow where it''s the lowest, and then the next phrase you''re bringing it up to another level where you''re getting close']::text[]),
  ('VghtMPTKvuI', 80, 116, ARRAY['The arm adds weight to your hand, adds weight to your bow, adds weight to your string.', 'Your arm is where all of this weight is originating.']::text[]),
  ('VghtMPTKvuI', 144, 160, ARRAY['Arm pressure is when you tense your muscles and try to push your bow into the string to create the sound.', 'That''s a little bit about arm weight.']::text[]),
  ('fcDc0clGE-U', 0, 49, ARRAY['If you just focus on the vertical component, that has to do with making sure that the bow bounces in rhythm and also in the right number of notes.']::text[]),
  ('Rpmg27DcOoU', 0, 15, ARRAY['OK, so let''s talk about how you keep your fourth finger round as opposed to letting it collapse, and I am struggling with this myself, and so when I thought about making this']::text[]),
  ('Rpmg27DcOoU', 23, 55, ARRAY['First finger, second finger, third finger, fourth finger.', 'I watched one of Professor V''s videos, he''s a very good violin teacher, if you haven''t gone by his site, Professor V, all one word, and I saw']::text[]),
  ('Rpmg27DcOoU', 112, 167, ARRAY['Motion I guess is what we''ll call it, so that I can wiggle my finger back and forth freely so that it comes out, rather than fight the physical impediments that are inherent in']::text[]),
  ('Rpmg27DcOoU', 144, 173, ARRAY['Here it moves a lot freer, so now let''s talk about that fourth finger, so when you are going for the fourth finger, be aware of where your elbow is underneath your violin, so if']::text[]),
  ('Rpmg27DcOoU', 178, 180, ARRAY['Far as distance is concerned, if my']::text[]),
  ('Rpmg27DcOoU', 300, 333, ARRAY['Is on the left side of my violin and I try to reach for the pinky, well, he''s gonna miss.', 'If your fingers are already collapsed inside out, then you''re pretty much doomed as']::text[]),
  ('jtnFBCcSnEA', 30, 54, ARRAY['If you can appreciate how hard that passage is, I haven''t played that for probably years, and so I need to practice, and that''s why I missed that top note.']::text[]),
  ('jtnFBCcSnEA', 175, 180, ARRAY['So you don''t have to press down at all because it''s heavier down here than it is up here.', 'When you''re up here, then you have to do something with your elbow so that the...']::text[]),
  ('7YvI9La1T2U', 7, 28, ARRAY['If you use too much bow, it''s going to slow you down a lot.', 'I had played it once back about 10 years ago, so I''m having a little bit of trouble remembering this, and I tried to practice a little bit']::text[]),
  ('7YvI9La1T2U', 133, 180, ARRAY['If I can hit this E flat, then I know that I can just put my fourth finger down and it''ll be the right note.', 'What I do to find that note, I''m actually doing a little mini shift with my second finger, this one right here.']::text[]),
  ('7YvI9La1T2U', 347, 360, ARRAY['It''s written missing the D string on the reverse chord.', 'This one has all four notes and the second one has...']::text[]),
  ('7YvI9La1T2U', 360, 408, ARRAY['I''m using a similar technique on the shifting as I did earlier, where I''m using the first finger to get the note from here.', 'I think they just want you to minimize the amount of sound that you get on the D string.']::text[]),
  ('7YvI9La1T2U', 391, 439, ARRAY['I''m using a similar technique on the shifting as I did earlier, where I''m using the first finger to get the note from here.', 'You have to give yourself a chance to put your finger down in the right spot before you pull here.']::text[]),
  ('7YvI9La1T2U', 420, 471, ARRAY['I need that otherwise I''m going to hear...', 'If I were to do it as though I were playing it, you hear that little space that I''m putting in my right hand?']::text[]),
  ('tOcpr1ZiYgo', 174, 179, ARRAY['Let me talk just briefly about a couple of these techniques.']::text[]),
  ('qdHbioZui2E', 599, 605, ARRAY['I have like random octaves jumping, I can''t even play them in tune, but the real trick']::text[]),
  ('P9A8mVGjERE', 0, 40, ARRAY['Ok, so for string crossings, as far as I understand it, this is how I practice it.', 'I think the A string is a good place to start, one of the two middle strings so that you have a way so you can go over to the left as well as to']::text[]),
  ('P9A8mVGjERE', 178, 180, ARRAY['I obviously don''t have my arm high enough.']::text[]),
  ('cdOu5rwy0Dc', 9, 60, ARRAY['One is string crossings and one is bow or arm weight.', 'String crossings and arm weight are going to be the two focuses.']::text[]),
  ('cdOu5rwy0Dc', 57, 106, ARRAY['So to practice that, first, play your first note, stop your bow, move to the D string using your arm.', 'I think it''s either keeping your shoulders down or it might be the string crossing one that explains that if you do it this way, you''re going to']::text[]),
  ('wd13P0yZpuU', 309, 324, ARRAY['I''m going to go a quarter, and then an eighth, and a sixteenth.', 'Those speeds do correspond, let''s say, if you take a quarter note and an eighth note.']::text[]),
  ('wd13P0yZpuU', 348, 360, ARRAY['So when I go for the fourth finger, for the other fingers I''ve pretty much kept my thumb in the same position, about first position.', 'Listen to your teacher first before you listen to me.']::text[]),
  ('kk6xaUwKCwg', 0, 14, ARRAY['"up-oh staccato" is a pretty tricky technique, and so I''m going to try to show you how I practice.', 'What I''ll do is I''ll start with an open string, with just maybe four notes, and make sure that each note at that speed is ringing and full of']::text[]),
  ('kk6xaUwKCwg', 153, 166, ARRAY['When you speed it up over time, you want to make sure that it''s always ringing, so that''s kind of the idea with up-bow staccato.']::text[]),
  ('Kobf2zvvvbk', 106, 162, ARRAY['Or you can even go... you can do 3/4 at the very end, although I don''t like to do that because my pinky is really weak on vibrato compared to my third finger.']::text[]),
  ('Kobf2zvvvbk', 126, 180, ARRAY['And then you can basically get it every time, as long as you practice really slowly to begin with.', 'Or you can even go... you can do 3/4 at the very end, although I don''t like to do that because my pinky is really weak on vibrato compared to my']::text[]),
  ('Kobf2zvvvbk', 329, 358, ARRAY['I think I did the wrong bowing but let''s first talk about the make sure you''re hugging those notes really tight again C sharps high, B flats and F''s low and I do like to start']::text[]),
  ('Kobf2zvvvbk', 446, 499, ARRAY['Something like that and so that''s the way that I would interpret it having not looked at this for years but apparently I can still play most of that because of the way that I''m']::text[]),
  ('neMlvsSMNEI', 0, 49, ARRAY['Today I''m going to demonstrate to you how to do false harmonics and I''m going to show you from Tchaikovsky''s Violin Concerto third movement, a very difficult passage.']::text[]),
  ('neMlvsSMNEI', 92, 133, ARRAY['So making sure that you''re moving your arm, that your arm is the one that''s making the shifting happen, so that when you do add your fourth finger down, you''re just keeping it at']::text[]),
  ('rQKX8Rl5O3w', 45, 58, ARRAY['This is the reason why I do it, is because when you''re playing the violin and you''re adding arm weight to your sound, which I discussed the difference between pressure and arm']::text[]),
  ('rQKX8Rl5O3w', 66, 123, ARRAY['Just for good practice measures for myself, to remind me not to put too much weight down, even if it''s something very loud and tumultuous, even if it''s chords, you don''t want to']::text[]),
  ('Hk97yKXBHVw', 22, 40, ARRAY['Then you have all these like really fast So what I''m doing is I''m doing a really really tight ricochet like And in order to do that I really have to tighten my my fingers Usually']::text[]),
  ('Hk97yKXBHVw', 116, 140, ARRAY['That and it''s actually kind of cool I like that because the harmonics can ring now the next part is False harmonics.', 'Let me show you You see how that''s a that''s making a fourth you can do it anywhere']::text[]),
  ('Hk97yKXBHVw', 173, 180, ARRAY['Then this part just jumps up so it''s basically combining the two it''s the slide and then the']::text[]),
  ('Hk97yKXBHVw', 180, 227, ARRAY['Then this part just jumps up so it''s basically combining the two it''s the slide and then the This is the distinct 3:00–3:47 occurrence.']::text[]),
  ('euQCJ6xqd94', 27, 43, ARRAY['That having been said, I have only had this piece for 24 hours, meaning I''ve only had maybe an hour or an hour and a half of practice on this piece.']::text[]),
  ('KAiPJsuDM50', 116, 169, ARRAY['I find it very lightly with your fourth finger and then speed it up a little bit.', 'Just extend your fourth finger out on that E.']::text[]),
  ('VYCyZFjBghs', 29, 44, ARRAY['Sit back and enjoy listen to my my Audition and don''t blindly vote I''d like you to listen to it and make sure that it''s a good take and if you really feel like I should go to']::text[]),
  ('Eri2MJKYxf8', 151, 175, ARRAY['Let''s go to the next step which is it''s a very simple kind of a staccato and all I''m doing at this point is doing the first motion I''ll show you with breaks at the ends of each']::text[]),
  ('Eri2MJKYxf8', 444, 479, ARRAY['In my fingers, now what I''m doing is I''m feeling a little bit of the bounce, of the natural bounce of the stick, which wants to bounce, I''m feeling it in my first finger.']::text[]),
  ('2FohGL_sGHI', 0, 27, ARRAY['If you practice it this way, where I am deliberately putting down my finger first and then moving my bow, putting my finger down, moving my bow, and so on, then']::text[]),
  ('ajbxxs-4SMk', 77, 102, ARRAY['Like that, then you would do it a little bit faster, after several days of practice.', 'I would do it very slowly, just like what I showed you here.']::text[]),
  ('ajbxxs-4SMk', 143, 178, ARRAY['To get your bow to not have trouble string crossing, I would probably practice this first with spaces.', 'That means I have to steal from the previous eighth note.']::text[]),
  ('ajbxxs-4SMk', 279, 320, ARRAY['What you should do is stop your bow before you change the string, stop, move, stop, well, I guess in this case it''s stop, move, stop, move, stop, move, stop, move, like that.']::text[]),
  ('Cu2dnhlKft0', 0, 25, ARRAY['Hey guys, starting today, Thursday night is going to be my practice night/YouTube night.', 'I''m kind of out of shape on my violin, and I''m going to start practicing in front of the camera, watch myself back, and try to improve.']::text[]),
  ('PTWDtHFcwIA', 156, 183, ARRAY['You stick it right up against your fourth finger so that what you can do is as you''re shifting instead of just trying to rely on this pinky, which I don''t know about you guys, but']::text[]),
  ('PTWDtHFcwIA', 180, 236, ARRAY['My pinky is my weakest finger and so when I try to find where it''s supposed to go, I']::text[]),
  ('dEVFN71MEGU', 303, 340, ARRAY['You''re going to hug your finger, your first finger, close to your second, and then to the A string on the C sharp, then back to the high one.']::text[]),
  ('EKeY_En_46g', 0, 46, ARRAY['Then what I want you to do is take your pinky and roll it and then undo it and then roll it and straighten it.', 'What I would recommend that you do is take your bow away so you have this and then bend your thumb.']::text[]),
  ('ewKUCf-ANlo', 653, 682, ARRAY['Three so one two four three two one so one two four three two one now I have to be careful because I I think my problem is not going up in this extension one two but getting back']::text[]),
  ('9evdTcBy5Hc', 27, 66, ARRAY['Put your first, second, third, fourth finger down like this.', 'We''re going to put the fourth finger next to the third finger right here so we can get a nice A-flat.']::text[]),
  ('t8CQXKgPNmc', 22, 68, ARRAY['It''s going to take a little bit of practice to get it right on, and pretty soon you can slide up to hit that top pinky.', 'That''s a pretty tricky shift, so you''re going to want to use the 2nd finger and go up to an E, right here, and then stick your 4th finger down.']::text[]),
  ('KCh3z314r5M', 386, 399, ARRAY['Then see now you could do slurs because you get this and then again with the contrast I kind of like that what I''m doing is I''m slowing two']::text[]),
  ('T12mQVEA6bM', 117, 173, ARRAY['With up-bow staccato, make sure that your right hand is very relaxed, so your fingers need to be very movable like this.', 'A note on these, make sure that you shift while you''re playing the open A''s.']::text[]),
  ('Qs-tFga-tVg', 35, 70, ARRAY['I speed this up very slowly, which is the key, by the way, to practicing or to playing very quickly, is to practice very slowly at first and then just increase your speed very']::text[]),
  ('aICv2fgoNg0', 86, 106, ARRAY['Because you want your fourth finger to be able to reach the fingerboard quickly.', 'If you''re over here with your hand pointed out like this, then it''s very hard to reach.']::text[]),
  ('aICv2fgoNg0', 369, 389, ARRAY['Shift during the open string, and that will get you there before you have to hear the notes in the next position.', 'Then it just keeps going ... 71 is kind of brutal.']::text[]),
  ('aICv2fgoNg0', 456, 504, ARRAY['If you''re going to practice that slowly, just make sure that this hand, the right hand is moving at the same pace so that all the notes sound even, not ...']::text[]),
  ('RToMe8Z6T2k', 360, 405, ARRAY['In orchestral playing because even when you''re practicing by yourself, you need to be hearing the beat because when you get back with the orchestra to practice, they''re not going']::text[]),
  ('69_-GJO5Z9M', 101, 151, ARRAY['When I go for this first shift, so I go to the fourth position and then pop my fourth finger down like that, and that gives me a really clean shift.']::text[]),
  ('69_-GJO5Z9M', 290, 313, ARRAY['Hand position, it doesn''t matter where I am on the violin, as long as I land into the correct land, and I''ve done this before, into the correct spot, then I will form an octave']::text[]),
  ('69_-GJO5Z9M', 390, 429, ARRAY['So I''m not moving my hand because I want to get all my other fingers to go into the right spots without throwing everything off, okay?', 'When you have to repeat a note in the same spot, make sure that you use your eyes, like sometimes people will let their eyes wander around']::text[]),
  ('69_-GJO5Z9M', 667, 720, ARRAY['Don''t let your fingers get too tall or too far over.', 'If you cannot articulate what position you''re in, then you probably need to think about it a little bit more because if you can tell what it']::text[]),
  ('NZVSQRzo48o', 309, 332, ARRAY['I kind of think that at 109 there should be', 'Don''t use too much bow either.']::text[]),
  ('Qa1Zj_L3x8c', 438, 464, ARRAY['The very first phrase takes about a quarter of that rainbow''s length.', 'Or maybe we should call it a rainbow because that''s the shape.']::text[]),
  ('IL4cmuWiQUk', 34, 92, ARRAY['When you take the scale, all of those eight notes, what you''re doing is you''re going up the scale, instead of going up the scale one scale step at a time, you''re going up two This is the distinct 0:34–1:32 occurrence.']::text[]),
  ('IDny7YYxobE', 88, 111, ARRAY['Our fingers can place anywhere on the string, it''s actually up to us to decide how distant each of those notes should be.', 'I''m not going to tell you how I''m doing it yet, but just see if you can tell what I''m doing.']::text[]),
  ('IDny7YYxobE', 360, 396, ARRAY['If I''m seeing this cat and he''s bald, I feel kind of bad, ?', 'In this opening, sometimes I think of it as like, I don''t know, what did we come up with in lesson?']::text[]),
  ('CvWVNMybMeQ', 76, 107, ARRAY['With hand position, I want to make sure that my hand, when I shift to a position, naturally forms an octave.', 'I think that I''m in fifth position right here.']::text[]),
  ('CvWVNMybMeQ', 123, 151, ARRAY['In reality, if I want to get an F up here, I''m actually in a different position.', 'I''m staying in position, but I keep hitting an F sharp.']::text[]),
  ('CvWVNMybMeQ', 164, 180, ARRAY['All of it fits between here, and the next fifth position is the extended fifth position.']::text[]),
  ('CvWVNMybMeQ', 356, 359, ARRAY['Then the next one, so all of that is built on the B flat']::text[]),
  ('3bAWqnjPfV4', 37, 86, ARRAY['You can either shift up to third position here, then shift back down or you can stay in first position I guess if you want to.', 'You can stop your bow because the first violin is still playing and the sound is still going so the audience will not be able to hear that.']::text[]),
  ('3bAWqnjPfV4', 88, 146, ARRAY['You can either stay in position here then come back down or at measure twelve you can also shift down here.', 'Notice that I shifted down on measure eight on the open string.']::text[]),
  ('3bAWqnjPfV4', 110, 167, ARRAY['You can either stay in position here then come back down or at measure twelve you can also shift down here.', 'I used that to shift down so it''s a measure seven last four sixteenth notes.']::text[]),
  ('3bAWqnjPfV4', 360, 395, ARRAY['When I''m shifting on measure twenty-seven, I''m using my first finger to go to third position first, and then using hand frame, which is basically when your hand is relaxed, your']::text[]),
  ('3bAWqnjPfV4', 404, 444, ARRAY['The reason why I''m doing that is so that I don''t have to really think of it about hopping my second finger over, otherwise how are you going to hit the G, the second note of']::text[]),
  ('3bAWqnjPfV4', 471, 518, ARRAY['I''m using the fourth finger here to help me to get from G straight', 'Up to third position for the next note in measure thirty.']::text[]),
  ('3bAWqnjPfV4', 723, 780, ARRAY['Measure forty-three, shift, shift, shift, and now you''re in first position.', 'I''m going to do it at C, measure forty-three.']::text[]),
  ('opNpw5mOowo', 141, 170, ARRAY['When you get your violin up, give yourself a breath, and then when you breathe in, get your violin up, and then from this position, just slowly, very slowly start taking in air.']::text[]),
  ('jrzuLv0ZT0w', 110, 130, ARRAY['The second part is to teach your hand where it is to land from relaxed position.', 'I''m going to do it a couple of times and just figure out where it''s supposed to go.']::text[]),
  ('G3MAdfyihhw', 164, 179, ARRAY['Now what I''m going to do is overlap each group by one note.']::text[]),
  ('l8EOOzC1xhE', 12, 41, ARRAY['Do that again, but very slowly bringing it to a position where you can play.', 'What I''d like you to do is take your bow, take your violin, and only using your arms, bring it to a playing position.']::text[]),
  ('SfwD0wHKqoI', 76, 98, ARRAY['When you''re shifting up, feel that slide, and then when your hand collides with the violin, hopefully not hitting it too hard, but when it collides with the violin, if it''s']::text[]),
  ('bdCSBvPyZCk', 23, 34, ARRAY['Each of us in position. [INAUDIBLE] Now, I''m going to turn around.', 'Sometimes you have to watch the balcony there.']::text[]),
  ('bdCSBvPyZCk', 111, 118, ARRAY['We should be in resting position.', 'Just carefully. [MUSIC PLAYING]']::text[]),
  ('c2GafXagxmk', 180, 196, ARRAY['Apparent on your A string.']::text[]),
  ('Qa1Zj_L3x8c', 349, 360, ARRAY['Try to use more bow at the beginning of your stroke and less bow at the end of your stroke.', 'Applies there on the double stops as far as how much bow you''re using.']::text[]),
  ('VghtMPTKvuI', 60, 76, ARRAY['Now when you contact the string with your bow, there are a few things that happen.', 'One is your bow is adding weight to the string.']::text[]),
  ('VghtMPTKvuI', 349, 362, ARRAY['Which is that your your wrist collapses we''ll call it so it falls down okay so that''s enough about the right hand left hand when you''re putting your fingers down on your']::text[]),
  ('Rpmg27DcOoU', 61, 112, ARRAY['If I were to bring my elbow under a little bit, now they''re starting to get a little bit rounder, so a lot of your hand position, at least for me, a lot of my hand position is']::text[]),
  ('QJL4rdBYbts', 4, 20, ARRAY['This is how I shift, and so I want to share this with you because when I shift, I''m not just moving my fingers to a spot, but I''m initiating the motion with my elbow, okay?']::text[]),
  ('QJL4rdBYbts', 97, 110, ARRAY['How do you make sure that you can hit that note?', 'You''re going into it, let''s see, you don''t want to miss that, it sounds horrible.']::text[]),
  ('QJL4rdBYbts', 161, 178, ARRAY['The same thing is true here where if you want to get a big shift, instead of focusing on how big the distance is up here for your little fingers, think of how small the distance']::text[]),
  ('QJL4rdBYbts', 287, 317, ARRAY['What I''m doing is I''m trying to figure out by feel how much my muscle moves.', 'Now that I''ve got that memorized, it''s actually only about this much that my muscle']::text[]),
  ('dFsLKLyDpFc', 99, 117, ARRAY['This is the way that I''ve found works the best, where you can lift up and down, and then my thumb being in this position, so that when I put my fingers down, they''re not...']::text[]),
  ('wd13P0yZpuU', 0, 52, ARRAY['So what I try to do is I try to get my hand into a very relaxed, comfortable position.', 'What I first do, let''s say I''m going to do a B on my first finger on the A string and C sharp, second finger.']::text[]),
  ('wd13P0yZpuU', 56, 79, ARRAY['What I''m doing is I''m just letting my finger start from up here and then fall down onto the string.', 'If you watch my other videos, I explain a little bit about why, or how I hold up my violin and why I do it.']::text[]),
  ('neMlvsSMNEI', 36, 68, ARRAY['When I get to this point, I will shift using my first finger like I would during the harmonics because I like that sound of the shifting.', 'The important thing here is to remember that your whole hand has to slide and your whole arm needs to be, or your elbow at least, needs to be']::text[]),
  ('Hk97yKXBHVw', 77, 96, ARRAY['That''s that''s the the point of reference I''m using so you don''t have to think of it as much of a shift As you should think of it as placing your hand where the body where the rib']::text[]),
  ('KAiPJsuDM50', 57, 89, ARRAY['Now you''re in second position, just stick your fingers down your first and fourth.', 'Then you have to shift down.']::text[]),
  ('dEVFN71MEGU', 345, 360, ARRAY['You''ve got like a fifth here, so you put your finger down on both strings, then you should be able to hear both the G sharp and the C sharp, and then down to the A sharp, which is']::text[]),
  ('dEVFN71MEGU', 360, 389, ARRAY['Shift up to the A sharp, which is a high third position, then a low on the D natural.', 'I''m using my third finger on both of those notes on the C sharp and the D.']::text[]),
  ('dEVFN71MEGU', 412, 427, ARRAY['One more time, and I''ll do it slowly so you can watch.', 'That''s what the interval is there.']::text[]),
  ('dEVFN71MEGU', 433, 453, ARRAY['Here, we''re in third position, we''re going to drop back down to first position and we''re just going to put our fourth finger down low on this A sharp.']::text[]),
  ('dEVFN71MEGU', 479, 501, ARRAY['I''m going to move my bow first before I shift.']::text[]),
  ('EKeY_En_46g', 109, 168, ARRAY['Then you should be able to get a nice relaxed bow grip.', 'In the next part, try to aim for the shift.']::text[]),
  ('ewKUCf-ANlo', 36, 66, ARRAY['Sorry D string for the D string three on the a string like this We could do two and one so a two on the D string like this in third position one right up against it Or I actually']::text[]),
  ('517uzXPQ3xg', 28, 77, ARRAY['One is that if I''m up on the third in third position I can control the vibrato on the D so it doesn''t sound so dry and also I like the fact that all of the notes are on the G']::text[]),
  ('517uzXPQ3xg', 590, 610, ARRAY['You have to hold it for that length.', 'Instead of doing this, which a lot of people will do, it''s just such a plain note.']::text[]),
  ('517uzXPQ3xg', 666, 722, ARRAY['Again, I''m jumping to the A string because I want that note to pop.', 'See, what I want is to have the C come out and then back off because']::text[]),
  ('517uzXPQ3xg', 745, 786, ARRAY['I do slur those really fast notes.', 'You can play that D the same way that you played the C, and it''s going to have a little bit more pop because it''s a higher note.']::text[]),
  ('9evdTcBy5Hc', 134, 162, ARRAY['If you have the ability to shift, then certainly you can do that, but for now we''re going to focus on the easiest fingerings.', 'Be very careful not to play this F, this right here, the first finger.']::text[]),
  ('t8CQXKgPNmc', 84, 137, ARRAY['You can do a nice little slide here, which is that it vibrates and then you use your arm to pull your finger until it moves.', 'You don''t actually move your finger down, you let it pull.']::text[]),
  ('t8CQXKgPNmc', 137, 180, ARRAY['These are not shifts that you normally do in most pieces, because you hear the slide.', 'If you don''t like it, don''t do it.']::text[]),
  ('t8CQXKgPNmc', 294, 339, ARRAY['I go up to the next string because I don''t want to go...', 'You have to go all the way up on the D string.']::text[]),
  ('t8CQXKgPNmc', 375, 418, ARRAY['Because I''m going to be moving to the E string pretty soon.', 'I also like using my third finger for fat vibrato.']::text[]),
  ('t8CQXKgPNmc', 445, 463, ARRAY['Now you can hear a little bit of my first finger.']::text[]),
  ('T12mQVEA6bM', 15, 38, ARRAY['Be in for a lot of practicing.']::text[]),
  ('T12mQVEA6bM', 147, 180, ARRAY['A note on these, make sure that you shift while you''re playing the open A''s.', 'That''s an opportunity for you to shift without hearing it. (upbeat violin music)']::text[]),
  ('69_-GJO5Z9M', 143, 180, ARRAY['Landon, we talk about this a lot, is when you have a hand frame in first position, you have a hand frame in third position, and that hand frame is forming an octave.']::text[]),
  ('69_-GJO5Z9M', 317, 360, ARRAY['Coming back down, it''s kind of similar, shifting backwards, a little bit different, but I do also use my arm to go back, probably my hand a little bit more just because, I don''t']::text[]),
  ('wLTDCW5Rv8o', 370, 396, ARRAY['My hand is wiggling, but most of the action is originating from my elbow down here, so if you can see that.', 'This is a complete exaggeration of the motion, but I''ll keep it typically around here just a little bit higher, and then when I vibrate and it']::text[]),
  ('Fic0zak8K5Y', 309, 330, ARRAY['Moving at a certain speed and keeping it at that speed so that all of those notes get used up by your bow during that one thing.', 'Watch how consistently it moves speed-wise.']::text[]),
  ('daQV_-LEb84', 0, 31, ARRAY['Ok, so what I''m doing here is I''m making the bow speed and the vibrato speed match all the way along the bow.', 'One of them is your bow speed and one is your vibrato.']::text[]),
  ('daQV_-LEb84', 44, 90, ARRAY['For instance, in the Mendelssohn''s second movement, when I start off, on that first bow, that down bow, I''m trying to swell the sound because I want it to be leading.']::text[]),
  ('daQV_-LEb84', 75, 133, ARRAY['For instance, in the Mendelssohn''s second movement, when I start off, on that first bow, that down bow, I''m trying to swell the sound because I want it to be leading. This is the distinct 1:15–2:13 occurrence.']::text[]),
  ('daQV_-LEb84', 110, 167, ARRAY['So what I''m doing here is I''m swelling first with my vibrato on that down bow, but not changing my bow speed.', 'So it''s a very difficult concept to explain as far as I''m trying to do it, but the basic idea is not to both your bow speed and your vibrato']::text[]),
  ('daQV_-LEb84', 133, 180, ARRAY['So it''s a very difficult concept to explain as far as I''m trying to do it, but the basic idea is not to both your bow speed and your vibrato speed.']::text[]),
  ('MC71NLSy3Dg', 575, 602, ARRAY['The piece on I believe, let''s see, I think I come in on a down bow.']::text[]),
  ('oVU8RYnnrzg', 139, 170, ARRAY['Regardless of which direction you''re moving your bow, this first stroke, which I think is an up bow, should receive the least amount of bow usage, of bow speed.']::text[]),
  ('4Hkm2kBu_mE', 279, 325, ARRAY['We have first thought, second thought, and then first thought again, and then we have this third thought that we need to also break up.', 'You can almost break that one up into two thoughts.']::text[]),
  ('kN1KNvbnL7Q', 298, 326, ARRAY['I guess what I''m trying to say here in analyzing what Vengerov just did, he''s using only the amount of bow that he needs to for those difficult passages, and']::text[]),
  ('ewKUCf-ANlo', 299, 318, ARRAY['The weight of your arm, this gravity weight that you''re feeling here, should stay consistent through this.', 'You can actually bend the pitch by pressing too hard.']::text[]),
  ('Fic0zak8K5Y', 19, 36, ARRAY['I like to think of this piece as more of a classically weighted piece, meaning not too much of that romantic stuff, and romantic stuff that I think of as wide vibrato, kind of']::text[]),
  ('Fic0zak8K5Y', 343, 364, ARRAY['Keep your bow speed the same, consistent through that whole stroke, that whole down bow, and then at the very end of that stroke, I''m increasing my speed just slightly, then I can']::text[]),
  ('opNpw5mOowo', 339, 359, ARRAY['You see how I''m taking no time on every note? (somber violin music) And you want it to feel like it''s this, the phrase is (sings)']::text[]),
  ('opNpw5mOowo', 360, 400, ARRAY['You got the first one. (somber violin music) Now don''t wimp out here, you don''t wanna go (somber violin music) I mean, you''re not giving, what happens is you lose the momentum']::text[]),
  ('opNpw5mOowo', 393, 441, ARRAY['Then now (somber violin music) and then you can back off a little bit. (somber violin music) And if at all you have, you''re questioning whether you''re supposed to be pulling your']::text[]),
  ('S-xMtLyNw1w', 0, 14, ARRAY['Let me just take a look at it real quick.']::text[]),
  ('S-xMtLyNw1w', 51, 65, ARRAY['What we''re trying to do with vibrato is to keep this nice and relaxed.', 'When you bring your hand up to play, make sure that it''s not ripping the neck and it just needs to be resting there.']::text[]),
  ('S-xMtLyNw1w', 148, 169, ARRAY['Where it should be originating is from this part of your body, the elbow', 'The vibrato motion, it looks like on your video, your vibrato is also originating from this spot right here where you may be squeezing.']::text[]),
  ('S-xMtLyNw1w', 359, 360, ARRAY['Good vibrato, rather than try to move your hand this way, stick your finger down, just']::text[]),
  ('MC71NLSy3Dg', 417, 434, ARRAY['These side to side again.']::text[]),
  ('cdOu5rwy0Dc', 127, 163, ARRAY['Then I would probably leave out vibrato for now because it does change some things.', 'Your bow will feel a little bit different when you''re vibrating because the violin does shake a little bit.']::text[]),
  ('76nciwj5cOU', 0, 57, ARRAY['I''ll post the links, but maybe what I can do instead is perform just a small passage of a piece for you and demonstrate how I like to do vibrato, and you can come on and ask me']::text[]),
  ('ZNxKJcSdMsU', 426, 466, ARRAY['I don''t want to spend too much time on that and then it gets into this.', 'Maybe these are the bells tolling again within his dream, bringing him back to reality.']::text[]),
  ('517uzXPQ3xg', 399, 424, ARRAY['Another trick to do before you make the bow change is to let up on the pressure.', 'That creates kind of this airy feel.']::text[]),
  ('517uzXPQ3xg', 617, 675, ARRAY['So growing usually means that you''re going to start moving your bow faster, or you''re applying more pressure, or you''re adding vibrato, or a combination of all three.']::text[]),
  ('wLTDCW5Rv8o', 9, 31, ARRAY['Anyways, today I''m going to talk about vibrato, and there are three issues that I''m going to address.', 'One is making sure that you don''t clamp down with your neck when you''re vibratoing.']::text[]),
  ('wLTDCW5Rv8o', 107, 130, ARRAY['When I''m vibrato-ing, it''s a combination of the two.', 'I don''t know what you guys think, but that''s how I play, is I let my neck sometimes']::text[])
),
matched AS (
  SELECT
    s.id,
    seed.contextual_clues
  FROM seed
  JOIN public.videos v
    ON v.youtube_video_id = seed.youtube_video_id
  JOIN public.segments s
    ON s.video_id = v.id
   AND s.start_seconds = seed.start_seconds
   AND s.end_seconds = seed.end_seconds
)
UPDATE public.segments s
SET contextual_clues = matched.contextual_clues
FROM matched
WHERE s.id = matched.id;

COMMIT;

-- Expected after seed: 301 matched segments with direct spoken-language clues.
-- Run the verification migration next before relying on this in production.
