-- 015_backfill_missing_contextual_clues.sql
-- Backfills direct transcript-context clues for segments that still had empty contextual_clues.
-- Generated from ~/Desktop/BenChanTranscripts using the corrected 180-second chunk cadence.

BEGIN;

WITH seed (youtube_video_id, start_seconds, end_seconds, contextual_clues) AS (
VALUES
  ('0f6n1HMHI6g', 122, 139, ARRAY['symphony if at all possible, so we''ll see how that goes. All right, so it starts at El De Gretto, 96. That''s the metronome marking. And this little pits, there are two of them and there''s a little circle with a line up.', 'And so what that means is a Bartok pits, which basically means and this is how I do the Bartok pits, there may be different ways to do it.']::text[]),
  ('0f6n1HMHI6g', 139, 152, ARRAY['basically means and this is how I do the Bartok pits, there may be different ways to do it. I take my two fingers, my thumb and my first finger and I pinch the string and then I pull up very slightly and then let go.', 'I''ll do that again, ready? Now don''t pull too high. If you pull too high, first of all you''re going to go out and pitch and second of all']::text[]),
  ('0f6n1HMHI6g', 152, 169, ARRAY['up very slightly and then let go. I''ll do that again, ready? Now don''t pull too high. If you pull too high, first of all you''re going to go out and pitch and second of all you might snap your string.', 'So not too high, maybe like, oh I don''t know, about this much up and down. I don''t know how much that is, maybe an inch? Well, that''s probably too high. So half an inch, how about?']::text[]),
  ('0f6n1HMHI6g', 163, 180, ARRAY['up and down. I don''t know how much that is, maybe an inch? Well, that''s probably too high. So half an inch, how about? And then what that does is it gives a snap.', 'The string comes down and snaps back against the fingerboard slightly. And if you do that with 40 violins as well as all the other instruments, then it makes a pretty cool little slap sound.']::text[]),
  ('0f6n1HMHI6g', 180, 209, ARRAY['So, when we first start off, we hear the lower strings do this pit, and then we do it. So it goes lower strings, so boom, boom, and then after the fermata, now it''s the other way around.', 'It''s us first, and then the lower strings, and then we go lower strings. Okay, so I''ll do that one more time. So boom, and then boom. Does that make sense?']::text[]),
  ('0f6n1HMHI6g', 210, 225, ARRAY['So it''s lower strings, then us, us and lower strings, and this is the first violin part, by the way. Okay, and then you have this ...', 'All these trills and so forth, and we''re doing this with the clarinets and a couple of the other woodwinds, as far as I know, and so we don''t have to overplay this.']::text[]),
  ('0f6n1HMHI6g', 225, 242, ARRAY['have to overplay this.', 'The most important part that I can see is the accent, so it''s the beginning of your note, and also don''t push too hard because there''s a lot coming up after this beginning, and so save your strength, because you want to be able to play the rest of it, and p...']::text[]),
  ('0f6n1HMHI6g', 242, 258, ARRAY['and so save your strength, because you want to be able to play the rest of it, and particularly at measure six, the very first quarter note of measure six, which is on the end of the first beat, so you have a tie, that very first one, don''t play too much th...', 'Play it very softly, so I''m going to start at measure five, and I''ll demonstrate what']::text[]),
  ('0f6n1HMHI6g', 258, 288, ARRAY['everything else.', 'Play it very softly, so I''m going to start at measure five, and I''ll demonstrate what I''m doing here, ready, and then an immediate decay right after that sporte piano there, and so if you do it this way, then you''ll conform to the overall sound of the orche...']::text[]),
  ('0f6n1HMHI6g', 313, 334, ARRAY['here to figure out how fast 140 is, it''s about this fast, let''s talk about this technique where you drop your bow, it''s a pretty cool little technique, and what I''m doing is I''m hovering over my strings using my bow, I have my hand totally relaxed here, so...']::text[]),
  ('0f6n1HMHI6g', 343, 360, ARRAY['it, but I''m basically, here, let me do it really slowly, a couple things that are very important here, one is you want to keep your bow hair flat, because the bow hair naturally wants to bounce, and if you''ve ever gotten nervous and you''re playing a really...']::text[]),
  ('0f6n1HMHI6g', 360, 381, ARRAY['to do is I want you to do the reverse of that. I want you to do relaxed hand and relaxed arm. But, start above the string and let it fall. And when I say let it fall, don''t let it fall like this. That''s wimpy. You get...', 'See, without anything else, if you''re just letting your bow fall, there''s no sound. What I want you to do is use your arm weight. So your arm falls with it. And also, make sure that that very first note before you have']::text[]),
  ('0f6n1HMHI6g', 381, 406, ARRAY['letting your bow fall, there''s no sound. What I want you to do is use your arm weight. So your arm falls with it. And also, make sure that that very first note before you have the ricochet... This is the ricochet.', 'Before you get to that ricochet, the note before that should be very, very, very, very short. Okay, you see that? And so, when you''re going between strings, you want to change the elevation of your arm.']::text[]),
  ('0f6n1HMHI6g', 406, 435, ARRAY['that should be very, very, very, very short. Okay, you see that? And so, when you''re going between strings, you want to change the elevation of your arm. So, if you''re on the G string, your arm should be pretty high.', 'If you''re going to do it on the D string, for instance, it''s the same concept, only I''m changing the height of my arm. Or, on the E string, or E string.']::text[]),
  ('0f6n1HMHI6g', 435, 460, ARRAY['E string. And so, that way, I don''t have to change the technique, only I have to change the angle of my arm. It does take a little bit more balance on the E string because you''re not quite vertical.', 'On the G string, it should be pretty easy, because you''re pretty much vertical. And you should be able to do this for hours. I''m not suggesting that you do that, but it should be so easy.']::text[]),
  ('1FN_xHL-u-Q', 195, 250, ARRAY['your bow, feel everything that''s happening. Feel it in your fingers, feel it in your wrist, your arm and your elbow and your forearm over here.', 'What I''m mostly concerned about is making sure that every note has a full tone to it. Maybe the reason why I don''t do scales a lot is because it''s boring. Because all you''re doing is just playing notes.']::text[]),
  ('1FN_xHL-u-Q', 250, 284, ARRAY['of something that comes to mind. What if you''re just doing something like that where you''re running up an arpeggio and you need that dexterity.', 'Well if you''ve been practicing it correctly, let''s translate that scale I was just playing into this arpeggio.']::text[]),
  ('1FN_xHL-u-Q', 497, 505, ARRAY['If it''s just a friend or something, but typically speaking, proper etiquette in a performer is to play a piece for the audience.', 'And so take that for what it''s worth and take this three octave scale for what it''s worth and see what you can do with it.']::text[]),
  ('1QFHZfQzZ0E', 196, 231, ARRAY['sounding... Instead of that, you get... And that gives the hair a chance to grip the bow and make it ring, like that. And then on that, that first chord is a little harsh. This part gives you a chance.', 'You can really be expressive here. It''s a melody, and it kind of comes out of almost nowhere.']::text[]),
  ('1QFHZfQzZ0E', 528, 539, ARRAY['And that''s the only way that I found play from this note to without getting that squeak where my pinky''s hitting the other string. So-- [MUSIC PLAYING] Whatever those notes are.']::text[]),
  ('3bAWqnjPfV4', 234, 287, ARRAY['when you''re supposed to come in. So you hear ... Now here you want to stop your bow in between each of the eighth notes. And that way you''ll mask the sound, or rather you''ll skip over the sound of the string crossing.', 'Otherwise you hear ... you''ll hear remnants of that middle string, you don''t want to do that.']::text[]),
  ('517uzXPQ3xg', 249, 274, ARRAY['because she''s just kind of thinking, "Well, do I really have a place to go? I don''t know." Now I like doing the little slur here at measure nine.', 'The way you accomplish that, so you have your B flat, then before you stop moving your bow, before you do the bow change, just start sliding your finger down nice and easy.']::text[]),
  ('517uzXPQ3xg', 540, 578, ARRAY['it comes out you can''t even hear the notes right it''s a little tricky to play that quickly so measure 19 you can either go to the the first position or and I actually in this one I don''t want it to pop too much so now that I think about it measure 20 maybe...']::text[]),
  ('517uzXPQ3xg', 811, 861, ARRAY['did. You pick whether you want to play down here or up here. I have a hard time vibrating really really big down here because my fingers hit the pegs. So I would recommend that you go this is measure thirty-eight.', 'Use the vibrato now instead of just the string to make it sound more bold and then back off on the vibrato when you get to the pickup to measure thirty-nine. So let me start measure thirty-seven. Now back off.']::text[]),
  ('69_-GJO5Z9M', 192, 227, ARRAY['correct land, and I''ve done this before, into the correct spot, then I will form an octave and it will sound fine. So...and then here...and that''s how I know that my fourth finger will land, where it needs to go.', 'Coming back down, it''s kind of similar, shifting backwards, a little bit different, but I do also use my arm to go back, probably my hand a little bit more just because, I don''t know, it''s harder to go down, in my opinion, and so I use a combination of my h...']::text[]),
  ('69_-GJO5Z9M', 230, 255, ARRAY['but going up I definitely just pretty much use my arm, and then my hand just slides to where it needs to go. So use this little trick that, when you want to shift properly, think of the name Landon.', 'You''re welcome, Landon. So the extensions are a little harder, right, because you have...and now you''re expected to hit up a little bit high.']::text[]),
  ('69_-GJO5Z9M', 1124, 1168, ARRAY['then. Okay, so that was another really good hand frame. So if you want to make sure you''re in tune here, figure out which position you''re in. Fifth position, so let''s see.', 'Then back down to third position, and there''s our little extension that I was talking about before where he''s like a little rogue, a little maverick. Don''t let him pull your whole hand into a different position.']::text[]),
  ('7YvI9La1T2U', 207, 225, ARRAY['Same thing here, this one. Again it''s another fourth. So use that little trick when you''re shifting on these and your intonation will be better. Let''s look down here a little bit. What about this...', 'So that''s an inverted chord.']::text[]),
  ('7YvI9La1T2U', 258, 291, ARRAY['Because the important notes on the reverse chord are the top two and the bottom. So as you''re not hitting, you''re hitting...', 'I''m using a similar technique on the shifting as I did earlier, where I''m using the first finger to get the note from here.']::text[]),
  ('9evdTcBy5Hc', 242, 271, ARRAY['finger is going to take the place of the second finger it''s gonna move down to that spot so now right here I''m gonna move it down so that I can put my first finger comfortably here and then back up or you could even put your fourth finger there in place of...']::text[]),
  ('CvWVNMybMeQ', 190, 234, ARRAY['the E natural. Now I''m actually in the E flat fifth and the reason why is because this first note is actually extended up into not a new position, just next to the second finger.', 'So as soon as I''m done playing this A, well, once I get to the next note, now you see where my finger is right now? Now I''ve got to walk it back a half step because this is the real position I''m in.']::text[]),
  ('CvWVNMybMeQ', 234, 269, ARRAY['bring it right back. That way I can hit the F. And then the next one, so all of that is built on the B flat major scale. Now is that the same position as the other one? It is.', 'So I can actually stay in position that whole time except for the C sharp right there. So don''t shift. Just let it pop up and pop back so it''s extending up and then going right back. Now it''s right back.']::text[]),
  ('E66s-OJI0m0', 232, 266, ARRAY['et cetera, et cetera. Let''s do some video game stuff. How about, oh, I can''t say the word of the name of the tune. How about... Yeah, so I think I still have... Let''s see if you guys can see this. Just one little']::text[]),
  ('EKeY_En_46g', 197, 231, ARRAY['I''m using 1-2-4. I''m not sure what that translates into on viola.', 'Here I''m staying in position, so shift, and then stay in position, only hop my third finger over, then extend up, and try to use your harmonics too, and that should help with your fingers.']::text[]),
  ('ETEads8iW24', 238, 266, ARRAY['What am I doing? Okay, I''m starting a little from just barely above the string and landing, and then as soon as I start landing, I pull. Well, I guess as soon as I start as I hit the string, so like this.', 'And Professor V also made a spiccato video. I think if you type in spiccato into the search, his will come up number two, but he has this thing where he''s talking about doing this, where you get this V shape.']::text[]),
  ('Eri2MJKYxf8', 188, 219, ARRAY['My fingers are also very loose. So now that you''ve got that movement, you have two movements, versus second. Now let''s go into the third, which is a little bit faster with the staccato.', 'All I''m doing is I''m using a little bit less bow, and I''m moving it twice as fast. Moving this part of my arm right here twice as fast. Make sure everything is staying very, very relaxed.']::text[]),
  ('Eri2MJKYxf8', 223, 253, ARRAY['We don''t want to get tense. If you do get tense at this point, go back to... And then get back into the staccato, until it feels completely comfortable, and then get into the double time.', 'Now what we''re going to do is we''re going to double the time again. My bow is not coming off the string.']::text[]),
  ('Eri2MJKYxf8', 266, 289, ARRAY['See that? Try that and see if it sounds the same. We''re about one step away from true spiccato, or sutie.', 'Now the sutie part comes in when you have your elbow raised just a little bit, just slightly, so that your wrist ends up a little bit higher than your hand. Just barely higher.']::text[]),
  ('Fic0zak8K5Y', 195, 248, ARRAY['So watch my bow. Watch how consistently it moves speed-wise.', 'All of that string crossings, if you haven''t watched my string crossing video, I would advise you to, but I''m doing it using my elbow only, so leading with your elbow and then it''s really easy after that.']::text[]),
  ('Fic0zak8K5Y', 532, 540, ARRAY['as that. And then it goes back into. Okay, it goes right back into that minor feel. Okay, so the, now where I am on the middle of the page. Now I''m going to rely.']::text[]),
  ('Fic0zak8K5Y', 540, 586, ARRAY['bit more on bow speed, whereas in the beginning I told you to start with a very consistent down bow. Now I want you to do a little bit more of a bow speed push and pull. I''m exaggerating some of that.', 'What I want here is for it to flow. I want the tempo to keep rolling forward because if you slow it down too much or if you don''t push it a little bit, it sounds very square, very robotic.']::text[]),
  ('G3MAdfyihhw', 185, 231, ARRAY['assume I didn''t watch their fingers, but I assume we just stay in first position this whole time through this whole piece, unless you have to go up to a higher note.', 'But so far it looks like everything is playable in first position. And then a little bit faster when you connect them. Then I''m going to try it with just four to a group.']::text[]),
  ('G3MAdfyihhw', 249, 284, ARRAY['doing it in threes. It would drive me nuts. I don''t think that''s a good idea. Never mind. Scrap that. But... Okay, now the bow stroke is... I think the bow stroke is a little bit of a... Kind of a spiccato.', 'Especially if you''re going at the speed that these kids are playing. Wow, I had some close calls there, but I think I got through it. What I''m doing is... There''s a little bit of a motion in my hand.']::text[]),
  ('G3MAdfyihhw', 540, 573, ARRAY['Okay, so I''m going to go, so kind of up, down, and then up, down, and then down, up, and because I''ve been practicing scales a lot, I already know that from here is, and then from, or from this, so as soon as I see this, I see, and I know that there''s a lit...', 'So when I look at it, and I just kind of eyeball it, oh yeah, it''s easy. Same with the second one.']::text[]),
  ('IDny7YYxobE', 208, 240, ARRAY['So if I played it normally, I guess I''m over-exaggerating the difference between equal temperament and the way that I''m explaining it that we could do to make it more minor, but versus...', 'This is a luxury that violinists have is that we can actually bend the pitch just a little bit to be a little bit lower.']::text[]),
  ('IL4cmuWiQUk', 180, 216, ARRAY['But when you have a run in a performance, you don''t really have to think about it.', 'So if I were to, let''s say for the sake of argument, I don''t know how to do thirds, and I get up on stage and I''m really nervous, and then when I have to play, and I think about every note, there''s no way in anywhere that you''ll be able to do musicality at...']::text[]),
  ('IL4cmuWiQUk', 217, 238, ARRAY['This is easy." And so now I''m going to think about the musicality. So something like that, and I ought to go back and practice that Beethoven.']::text[]),
  ('IZhlanwZPS8', 560, 590, ARRAY['I can''t emphasize enough practicing this slow.', 'Now I just sight read this because I guess it''s very classical in nature, and so because I have perfect pitch, it''s probably easy for me to tell what the notes are that are coming.']::text[]),
  ('KAiPJsuDM50', 193, 245, ARRAY['those kind of fast notes. And so I split it up in the transcription as a triplet and then four sixteenths. I would probably slur those. In fact, I think maybe he slurs them all together. I''m not sure.', 'Now here, I think he might be going first position. This is measure 43, shifting up to second position, back to first position. Something like that. So 42. Then he does another one of those slides.']::text[]),
  ('KAiPJsuDM50', 231, 279, ARRAY['shifting up to second position, back to first position. Something like that. So 42. Then he does another one of those slides. Let''s see, all the way up to right there. So you have to figure out where that is.', 'Practice sliding up and down until you get comfortable with it. And then watch your fingerboard to figure out exactly where it is when you''re playing it. The rest of this stuff.']::text[]),
  ('Kobf2zvvvbk', 486, 537, ARRAY['So go ahead and watch that one, again with the shifting, make sure that you are doing a gradual shift and not super fast shift, in fact I think I also have a video called Ben Chan Shifting, so you may want to watch that too, in fact just watch the videos.', 'Let''s see, the best I can do though right now is show you how I do it, how I apply it in this, let''s see, let''s go to...']::text[]),
  ('Kobf2zvvvbk', 540, 596, ARRAY['and also these runs. Now, I do a little bit of a cheat on the three. You should probably use your fourth finger. I''d recommend that. I''m just playing around. Okay, let''s keep going.', 'We want a, or at least I want to hear, a very sweet tone, which requires more of your bow speed and less of your vibrato. We don''t want a really intense. You see how that''s a little overboard for where we are right now.']::text[]),
  ('MC71NLSy3Dg', 192, 215, ARRAY['it''s very difficult.', 'But if you are an advanced player and you want to add a little bit to your playing, I would experiment a little bit with that in adding a little bit of extra pitch going upwards on the E and the B in the opening.']::text[]),
  ('MC71NLSy3Dg', 503, 524, ARRAY['You coast into the arrival, and then it feels like a normal phrase, like a very continuous phrase. And I saved most of my playing around with this amount of bow speed, I saved that for after that beat. Now here...']::text[]),
  ('MRtvUvg5Afs', 259, 268, ARRAY['fat hands, skinny hands, whatever. I kind of feel like I have a good hand for the bow because I have skinny fingers but they''re long, so they''re able to just kind of go like this.', 'Work with your teacher on that, but that''s kind of how I do my bow grip.']::text[]),
  ('PTWDtHFcwIA', 214, 256, ARRAY['which forms an octave between the two strings. And so that helps. The other thing that I would suggest is to listen to the bottom note and tune always to the bottom note.', 'So as long as your first finger''s moving, as long as it''s in tune then the top one can tune against it. And then finally the last piece of advice I''d give you is relax.']::text[]),
  ('QJL4rdBYbts', 239, 256, ARRAY['Even if you aren''t consciously thinking about it, your muscle remembers how big that distance is. Like I used to. And then your shifting suddenly becomes a lot better.', 'So the most important thing to learn from this video, this very short video, is focus on the bigger muscles and the smaller muscles will follow.']::text[]),
  ('Qa1Zj_L3x8c', 193, 242, ARRAY['initiating the motion. When you get to this point, you''re going to want to bring your elbow up before you change your bow stroke, which direction your bow is moving. You don''t get any weird sounds like.', 'I''m trying to help you to get to that double stop without any breaking of the sound, because then you lose some musicality if you do that.']::text[]),
  ('Qs-tFga-tVg', 185, 237, ARRAY['little tiny accents with my bow to make it sound like it''s still string crossings even though they''re not. Make it sound uniform. Let''s keep going.', 'At this point, this is measure 15, I like to shift up to third position and using the A string to mask that shift so you can''t hear it.']::text[]),
  ('Qs-tFga-tVg', 208, 256, ARRAY['can''t hear it. Yeah, make sure you hit that A right on because you can tell if the A is out of tune. This last one I like to do on the C#, I like to go up to third position again.', 'Okay, so this very last part is just a scale up, a minor scale. So the only advice I can really give you there is because it''s so quick and so fast, make sure you practice it very slowly to begin with.']::text[]),
  ('RToMe8Z6T2k', 240, 261, ARRAY['to 41. So you''ve got one, two, one, two, one, two, one, two, one, two.', 'This is very important in orchestral playing because even when you''re practicing by yourself, you need to be hearing the beat because when you get back with the orchestra to practice, they''re not going to wait for you or accept your speeding up.']::text[]),
  ('Rpmg27DcOoU', 194, 245, ARRAY['it over and he starts to hit it, but when I when I hit down, you either come out like this, you know, something that is totally not good because if your first knuckle is collapsed, then you can''t do anything.', 'You''re stuck. The vibrato action relies on that first knuckle collapsing. It''s this action here. So, if your fingers are already collapsed inside out, then you''re pretty much doomed as far as vibrato is concerned.']::text[]),
  ('Rpmg27DcOoU', 242, 286, ARRAY['but it comes out like this. Can you see that? Where just the first knuckles collapse and the second knuckle is not. I think I can do it with other fingers. Yeah, like this. Only out of her pinky.', 'So, her pinky ends up looking like this.']::text[]),
  ('S-xMtLyNw1w', 207, 262, ARRAY['than pushing my finger down like this, where it''s going to really tire out your finger, I''m just bringing my elbow over, and in so doing, my finger just naturally collapses that way. Same thing with my pinky. See that?', 'So I''m not pushing my pinky down like this to make it happen, I''m just bringing my elbow this way, in this horizontal motion.']::text[]),
  ('T12mQVEA6bM', 253, 290, ARRAY['Okay, let''s keep going. Now these octaves, make sure you lead with your lower note. Your higher note will just kind of follow along, forming that nice square hand position. Like this.', 'Then up-bow staccato all the way to the end. And that is the video tutorial of Samvel Yervenyan''s Violin Solo. So please let me know how this tutorial went.']::text[]),
  ('VghtMPTKvuI', 254, 273, ARRAY['violin up and you let your arm kind of fall your finger will then fall into the string so okay so you see this little action here that I''m doing with my third finger I''m dropping it into the string with just my arm weight to coming through a little bit tric...']::text[]),
  ('aICv2fgoNg0', 223, 269, ARRAY['So by the time you get all the way down to 47 or actually 43 ... Now, I''m not exactly sure if these are the right notes, but at 54, I put open strings.', 'I think he does that because then in order to get up to third position on 55 to hit this, he''s actually going ... You see how I''m using the open strings to get up there? You can use that technique almost anywhere.']::text[]),
  ('aICv2fgoNg0', 264, 294, ARRAY['Then it just keeps going ... 71 is kind of brutal. So slow motion. This is one of the ones that I hate the most is in first position trying to get from 1-3 to 2-4 because if you touch the A string ...', 'So I''m trying to play on the D string. If you touch the A string with your pinky, it''ll kind of make this weird squeaky sound.']::text[]),
  ('ajbxxs-4SMk', 210, 233, ARRAY['I guess in this case it''s stop, move, stop, move, stop, move, stop, move, like that.', 'And so what this will do is it''ll teach your bow to stop before you change strings, and this will allow you not to hear the sound in between the string change.']::text[]),
  ('c2GafXagxmk', 245, 281, ARRAY['forward. In any case, it''s not what you want to do. One more demonstration. One other thing I could add, maybe just to help you with the next step, once you''ve got this feeling down, is to vary your bow speed.', 'It sounds a little bit sterile. I don''t know where you''re at as far as vibrato is concerned, but even with just your bow, start it off a little bit faster and slow it down.']::text[]),
  ('dEVFN71MEGU', 234, 263, ARRAY['should be able to hear both the G sharp and the C sharp, and then down to the A sharp, which is a low one. Now I''ve got a little bit of a shift here.', 'Shift up to the A sharp, which is a high third position, then a low on the D natural. Now I''m using my third finger on both of those notes on the C sharp and the D. That''s where you get the little slide.']::text[]),
  ('eh_5PwiFJoU', 213, 240, ARRAY['Okay, if you hit that one, then that one will ring in the lower note, and if you hit in between there, then you get much less resonance.', 'So listen for those open strings, and a good exercise is to play a scale against one of your open strings.']::text[]),
  ('eh_5PwiFJoU', 245, 272, ARRAY['and feel it resonating, and by playing the other string at the same time, you''ll feel it more so in your hand, it amplifies the feeling.', 'So give that a shot, and hopefully, by the time you get to playing your scales a little bit faster, you can mostly get it in tune and feel it in your left hand as well as in your ear. So good luck!']::text[]),
  ('ewKUCf-ANlo', 180, 198, ARRAY['Yeah, you can actually bend the pitch by pressing too hard. Also be careful of your pinky. Don''t press too hard on your pinky. Leave it nice and relaxed.', 'The weight of your arm, this gravity weight that you''re feeling here, should stay consistent through this.']::text[]),
  ('ewKUCf-ANlo', 238, 294, ARRAY['one. This one just kind of stands on its own, doesn''t it? Okay so we''ve got, oh yeah, so the next part after all the tutti stuff from the orchestra. I really like this. This is really nice.', 'You want to make this as rich sounding as possible. So what I''m doing is I''m keeping a very warm vibrato, which usually means a very wide vibrato.']::text[]),
  ('ewKUCf-ANlo', 556, 580, ARRAY['hall is very large and you need to get your sound to carry, you''re going to want to put a lot of weight into this. Not with your pinky. Don''t push with your pinky.', 'I tend to, when I''m rusty, I tend to use my pinky to press down and then I watch my YouTube videos back and say, "Hey, Ben, what are you doing?" So don''t press down like this. Just have your arm weight, okay?']::text[]),
  ('g-Df8xaScUM', 350, 360, ARRAY['♪♪ ♪♪']::text[]),
  ('g-Df8xaScUM', 384, 401, ARRAY['Sometimes I squeak because my bow is going slanted, and it''s going slanted this way towards the fingerboard, so I''ve got to watch that too, particularly during those eighth note runs, and there''s my pinky going straight again.', 'I think it''s just undue stress, and I don''t think I need to do that. Now this time, I did it on purpose. I started closer to the fingerboard because it gives more of a thin sound, and that''s']::text[]),
  ('g-Df8xaScUM', 407, 435, ARRAY['I started closer to the fingerboard because it gives more of a thin sound, and that''s what I wanted. I''m trying to lean on the voice that is the melody, again, with the straight pinky. Gotta watch that.', 'I think I carried the melody pretty well there, and I was trying to pace it so that it was still carrying, even though that gets very difficult technically.']::text[]),
  ('g-Df8xaScUM', 438, 474, ARRAY['still carrying, even though that gets very difficult technically. I didn''t want the audience to know that.', 'Again, I''m starting to get a little bit stiff, more on the other fingers than my pinky, so I''ve got to watch that because it was getting hard technically, and I can''t let that stop me.']::text[]),
  ('g-Df8xaScUM', 556, 595, ARRAY['not be an F sharp. That should be an F natural, so I''ve got to watch that. I remember I used to play it wrong, and it came back for some reason.', 'And then my D and F sharp on that lower chord, D, F sharp, C was out of tune. I should probably emphasize the melody that''s on the G string a little bit more during that time, carry it more. It got cut off a little bit.']::text[]),
  ('jrzuLv0ZT0w', 180, 199, ARRAY['that''s pretty good. So the same thing will apply then for your other fingers. The trickiest one is your pinky. I''m not going to demonstrate that one because I haven''t quite gotten it right yet.', 'But the other fingers, my hand remembers when I put it down that it has to go forward a little bit. And it''s mostly this one is just in my hand. It''s just a very small gesture so I']::text[]),
  ('kp4eS5hMI24', 491, 540, ARRAY['one, each of those has to be different. And so the way that I''m doing it is the very first two of those sharp notes, I''m doing them very decisively the first time.', 'And then the second time, a little bit more legato and a little bit wider vibrato. And the last one I''m doing a little bit even more vibrato and more legato and less edgy, less sharp.']::text[]),
  ('mjTr6fKPgBM', 180, 187, ARRAY['Except I also have to clip that first, or the harmonic, in order to get to the next [BLANK_AUDIO]']::text[]),
  ('mjTr6fKPgBM', 224, 273, ARRAY['have I decided now after watching? So now I''ve got to get to the next phrase, which is ... So I have to differentiate between these two phrases.', 'The second phrase I haven''t played yet, but it''s kind of a repeat, a secondary thought that is related to the first thought. So now I have two thoughts that I need to put together.']::text[]),
  ('neMlvsSMNEI', 214, 234, ARRAY['past your third finger.', 'Oftentimes, we''ll undershoot because we''re not thinking about it, but in reality, the easiest way that I have found is to move my whole arm to fourth position as soon as I finish going to the A, and that''s how I make sure that I get that in tune, so good luck.']::text[]),
  ('o-5jCSWJKwc', 203, 238, ARRAY['achieve that sound that I want. And so when I''m going through I also want it to swell. I want it to go and then back off.', 'So I''m going to try to put that into practice and then what I do is I relax and then keep on my bow because if you don''t pull your bow you don''t get any sound. So relax, keep on your bow and then start going.']::text[]),
  ('opNpw5mOowo', 507, 540, ARRAY['Whereas here, now it''s more of a dignified... Sorry. Well, if you''re wondering about that fingering, I would shift here and then shift here. In fact, you can get it a little bit of a, let''s see.']::text[]),
  ('qdHbioZui2E', 240, 260, ARRAY['(violin music) (violin music) And then just little tiny bits of vibrato. (violin music) What I''m doing instead of vibrato is I''m using my bow speed to dictate how the phrase, or how the notes are phrased. So.', '(violin music)']::text[]),
  ('qdHbioZui2E', 357, 359, ARRAY['And it just keeps going on and on and on. we already have.']::text[]),
  ('rQKX8Rl5O3w', 217, 234, ARRAY['so again when I tighten it I usually tighten it just about to the point where you can fit this width in between the stick and the hair and then when I play I try not to press down where it hits the hair and that way I know that I''m not putting too much arm...']::text[]),
  ('rgmXFfudqUY', 267, 292, ARRAY['shoulder down and just use your forearm and your elbow. What that does is it actually ends up making your bow angle this way. See how it''s tilted this way just a little bit? So it starts off.', 'This establishes another thing for you. It keeps your contact point with the string at the exact same spot on the bow. You see this? It''s staying at the exact same spot all the way up.']::text[]),
  ('rm3BYJa5z1s', 175, 180, ARRAY['[Music] [Music]']::text[]),
  ('t8CQXKgPNmc', 205, 223, ARRAY['Which might sound a little bit cleaner. Now, this one''s fun. You have to go all the way up on the D string. Okay, up to third position, like third and a half. Now, up to fifth. Now, up to seventh.', 'You should be playing pretty close to the bridge, but not too close to the bridge.']::text[]),
  ('t8CQXKgPNmc', 226, 285, ARRAY['You should be playing pretty close to the bridge, but not too close to the bridge. And don''t press too hard. Let it ring. Lots of vibrato. And back down to third and a half.', 'And make sure you don''t miss that pinky like I did. Because you''re going down here. See, the distance here is pretty big. So you have to actually reach over pretty far to get back up.']::text[]),
  ('tHVk9XfXUC4', 200, 236, ARRAY['way with breaking the chord where I''m giving the emphasis to the bottom two notes and then letting that, as the amplitude gets smaller, letting it coast out into the string cross.', 'Now when you cross the strings, I have a string crossing video, make sure that it''s your elbow that''s determining what string you''re on because if you try to break it like this, try to use your wrist, you''re going to get some kind of a jump in your sound an...']::text[]),
  ('tHVk9XfXUC4', 236, 261, ARRAY['You get a locked wrist somehow and so if you''re doing it relying just on your elbow, just your elbow is the one that''s helping.', 'Now your wrist can do a little bit just in the fine tuning of where that lands, but make sure it''s your elbow that leads the motion.']::text[]),
  ('tOcpr1ZiYgo', 180, 209, ARRAY['It''s just a very light up-bow, I guess it''s kind of up-bow staccato, but very, very light. Maybe flying up-bow staccato.', 'It''s like my arm, which is typically what causes me to go up the bow, is kind of getting ahead of itself. As I gradually get through, it''s my arm getting too ahead of it and then slowing down, so']::text[]),
  ('wd13P0yZpuU', 211, 227, ARRAY['should be twice as fast as the half distance. So you hear that? So now let''s talk about the fourth finger, which is the hardest one for me anyways. Okay, here''s a little trick that I do.', 'And you''ll have to talk to your teacher to see if this is legit or not, because I don''t know.']::text[]),
  ('wd13P0yZpuU', 230, 288, ARRAY['Listen to your teacher first before you listen to me. This is just an idea you can maybe play with.', 'Okay, so when I go for the fourth finger, for the other fingers I''ve pretty much kept my thumb in the same position, about first position. Now when I bring my fourth finger down, I''m going to do a couple things.']::text[])
),
updated AS (
  UPDATE public.segments s
  SET contextual_clues = seed.contextual_clues
  FROM seed
  JOIN public.videos v ON v.youtube_video_id = seed.youtube_video_id
  WHERE s.video_id = v.id
    AND s.start_seconds = seed.start_seconds
    AND s.end_seconds = seed.end_seconds
    AND coalesce(array_length(s.contextual_clues, 1), 0) = 0
  RETURNING s.id
)
SELECT count(*) AS backfilled_contextual_clue_rows FROM updated;

DO $$
DECLARE
  remaining_count integer;
BEGIN
  SELECT count(*) INTO remaining_count
  FROM public.segments
  WHERE coalesce(array_length(contextual_clues, 1), 0) = 0;

  IF remaining_count <> 0 THEN
    RAISE EXCEPTION '015 aborted: % segment(s) still have empty contextual_clues', remaining_count;
  END IF;
END $$;

COMMIT;

