-- 017_semantic_drift_cleanup_batch_1.sql
-- Conservative semantic cleanup for high-confidence ai_proposed drift rows.
-- Keeps rows unpublished; improves title/use/summary/tags from direct transcript clues.

BEGIN;

WITH fixes AS (
  SELECT *
  FROM (
    VALUES
      ('1FN_xHL-u-Q', 0, 51, 'Scale Practice: Framing the Purpose', 'the player is using scales as a technical frame rather than a passive warmup', 'The transcript is introducing how to approach three-octave scales. Treat the scale as a focused technical study, then decide what specific variable the scale is meant to clarify.', 'scale work is being treated as generic note-running', 'starting scales without naming the purpose of the repetition', 'Before playing, name one scale goal: tone, intonation, relaxation, shifting, or evenness.', 'Could you say what this scale repetition is supposed to teach?', ARRAY['scales','practice-strategy']::text[]),
      ('1FN_xHL-u-Q', 46, 87, 'Three-Octave Scales: Intonation and Relaxed Shifts', 'the player is using a scale to connect intonation, consistent sound, and relaxed shifting', 'The clue names intonation, consistency of sound, and shifting on repeated D notes. Use the scale to keep pitch and tone stable while the shift stays physically relaxed.', 'intonation and sound change when the shift appears', 'tightening the hand during the shift and losing tone consistency', 'Play the shift notes alone, then reconnect them into the scale while checking tone and relaxation.', 'Did the shift preserve both pitch and sound quality?', ARRAY['intonation','shifting','scales']::text[]),
      ('1FN_xHL-u-Q', 250, 284, 'Scales to Arpeggios: Translating Dexterity', 'the player wants scale practice to transfer into arpeggios and passagework', 'The clue connects scale practice to arpeggio dexterity. Practice the scale pattern as a transferable motion, then test whether it makes the arpeggio feel organized.', 'scale work is not transferring into the passage that needs dexterity', 'practicing the scale separately without applying its hand pattern', 'Play the scale fragment, then immediately play the related arpeggio with the same relaxed setup.', 'Did the scale make the arpeggio easier to organize?', ARRAY['scales','practice-strategy']::text[]),
      ('1FN_xHL-u-Q', 311, 351, 'Three-Octave Scales: Feel the Whole Motion', 'the player wants a full scale to stay in tune, consistent, and relaxed through the whole body', 'The clue asks the player to feel the fingers, wrist, arm, elbow, and forearm while keeping tone, intonation, and relaxation through the scale.', 'the scale is technically correct in notes but tense or uneven in the body', 'monitoring only the left-hand notes while ignoring arm and wrist feedback', 'Play one octave slowly and scan fingers, wrist, arm, elbow, and forearm for unnecessary tension.', 'Could you keep the tone and intonation while the whole motion stayed relaxed?', ARRAY['scales','intonation','bow-relaxation']::text[]),
      ('1FN_xHL-u-Q', 360, 418, 'Scales and Bowing: Half Notes Per Bow', 'the player is connecting scale work to bow distribution and note grouping', 'The clue says the scale is being played as half notes per bow. Use the scale to clarify bow grouping and the relationship between note length, bow use, and sound consistency.', 'the scale is practiced without a clear bowing or grouping plan', 'changing bow use accidentally instead of assigning it deliberately', 'Play the same scale with one clear bowing rule, such as half notes per bow, and listen for even tone.', 'Did the bowing plan make the scale more consistent?', ARRAY['scales','bow-changes','bow-speed']::text[]),
      ('1QFHZfQzZ0E', 196, 231, 'Performance Context: Expressive Entrance', 'the learner wants to hear how a melody emerges and how harshness gives way to expression', 'The clue describes a harsh first chord followed by a chance to be expressive as the melody comes out of almost nowhere. Treat this as performance context for shaping character and entrance quality.', 'the passage is reduced to bow relaxation when the clue is mainly musical character', 'solving the excerpt only as a mechanics issue instead of shaping the entrance', 'Listen for where the sound stops being harsh and starts becoming expressive.', 'What character change do you hear at the entrance?', ARRAY['performance-context','genre-style','bow-relaxation']::text[]),
      ('1QFHZfQzZ0E', 367, 381, 'Performance Context: A New Layer of Musicality', 'the learner wants to understand how a repeated idea can reveal added musicality', 'The clue is about giving the audience a new layer of musicality. Frame this as performance context: the value is in hearing how the passage changes for the listener.', 'the row was framed as double stops even though the clue is about audience perception and musical layers', 'treating the excerpt as a narrow interval exercise', 'Listen twice and name what new musical layer appears the second time.', 'What does the audience hear that was not present before?', ARRAY['performance-context','genre-style','perceived-difficulty']::text[]),
      ('1QFHZfQzZ0E', 425, 444, 'Performance Context: Lyrical Flow', 'the learner wants to hear a lyrical, flowing passage as a model of musical character', 'The clue says the passage is lyrical and flowing. Use it as performance context for line, character, and continuity rather than as a fourth-finger diagnosis.', 'a lyrical excerpt is mislabeled as a narrow left-hand task', 'listening only for mechanics and missing the musical flow', 'Listen for how the line keeps moving without sounding mechanical.', 'Does the passage feel lyrical and flowing?', ARRAY['performance-context','genre-style','bow-speed']::text[]),
      ('1QFHZfQzZ0E', 467, 477, 'Performance Context: Making the Difference Audible', 'the learner wants a repeated or related passage to sound distinct enough to stay engaging', 'The clue asks for a distinction so the music does not all sound the same. The useful task is performance contrast: make the difference audible and engaging.', 'the excerpt is treated as a left-hand issue when the clue is about musical contrast', 'playing related material without enough character difference', 'Play the two ideas back to back and exaggerate one contrast in color, timing, or emphasis.', 'Could a listener hear the difference immediately?', ARRAY['performance-context','genre-style']::text[]),
      ('1QFHZfQzZ0E', 528, 539, 'Fourth Finger: Avoiding the Squeak', 'the player needs the pinky to clear neighboring strings cleanly', 'The clue directly names a squeak caused by the pinky hitting another string. Keep the fourth finger accurate and compact enough to avoid accidental contact.', 'the fourth finger touches a neighboring string and creates a squeak', 'placing the pinky too broadly or without checking clearance', 'Place the fourth finger silently, check that it is not touching the other string, then play.', 'Did the note speak without a pinky squeak?', ARRAY['fourth-finger','string-crossing']::text[]),
      ('3bAWqnjPfV4', 37, 86, 'Shifting: Optional Position Choices', 'the player is deciding whether to shift up and back or remain in first position', 'The clue presents position-choice options and notes that a stop in the bow can be hidden by the continuing first violin. Decide the position plan around both ease and what the audience hears.', 'position choices are made without considering musical cover', 'shifting just because it is possible instead of choosing the cleanest option', 'Try both the shift and first-position option, then choose the one that sounds least exposed.', 'Which option sounds cleaner in context?', ARRAY['shifting','performance-context']::text[]),
      ('3bAWqnjPfV4', 88, 146, 'Shifting: Using the Open String to Hide Motion', 'the player is shifting down while using an open string or musical context to mask the movement', 'The clue points to shifting down around measure eight and staying or returning to position. Use the open string and surrounding texture to make the position change unobtrusive.', 'the shift is audible or poorly planned in the phrase', 'moving positions without using the available musical cover', 'Isolate the measure-eight shift and time it with the open-string cover.', 'Did the shift disappear into the phrase?', ARRAY['shifting','performance-context']::text[]),
      ('3bAWqnjPfV4', 151, 180, 'Fourth Finger vs E String: Choosing the Easier Route', 'the player is choosing between extending to fourth finger and moving to the E string', 'The clue says the fourth-finger option is harder and that the E-string option may be easier. Choose the fingering that gives reliable sound and intonation for the passage.', 'the player forces a harder fourth-finger option when a string change may work better', 'treating the written fingering as mandatory instead of comparing routes', 'Try the fourth-finger version and the E-string version, then keep the cleaner one.', 'Which route sounds easier and more reliable?', ARRAY['fourth-finger','string-crossing','intonation']::text[]),
      ('3bAWqnjPfV4', 234, 287, 'String Crossing: Stop the Bow to Mask the Middle String', 'the player hears unwanted remnants of the middle string during a crossing', 'The clue says to stop the bow between eighth notes so the sound of the string crossing is masked. The goal is a cleaner crossing without leftover middle-string noise.', 'string crossings leave audible remnants of the middle string', 'letting the bow smear through the crossing instead of stopping cleanly', 'Practice stop, move, play on the crossing until the middle string disappears.', 'Did the crossing sound clean without the extra string?', ARRAY['string-crossing','bow-changes']::text[]),
      ('3bAWqnjPfV4', 272, 311, 'Fourth Finger: Use It for Long Notes, Avoid It for Fast Ones', 'the player is deciding when fourth finger sounds better than an open string', 'The clue says fourth finger can sound less harsh on long notes, but fast sixteenth notes may call for a different choice. Match the fingering to note length and sound quality.', 'the same fingering choice is used regardless of speed or tone', 'using fourth finger automatically even when the passage is too fast', 'Compare fourth finger and open string on the long note, then test the fast note separately.', 'Which fingering gives the better sound for this note length?', ARRAY['fourth-finger','performance-context']::text[]),
      ('3bAWqnjPfV4', 360, 395, 'Shifting: First Finger Leads to Third Position', 'the player uses first finger and hand frame to organize a shift into third position', 'The clue names shifting with first finger to third position first, then using a relaxed hand frame. Let the first finger organize the landing before the rest of the hand follows.', 'the hand arrives without a reliable frame in third position', 'jumping the whole hand instead of letting first finger organize the shift', 'Shift only with first finger, pause to feel the hand frame, then add the rest of the notes.', 'Did the first finger create a stable third-position frame?', ARRAY['shifting','intonation']::text[]),
      ('3bAWqnjPfV4', 471, 518, 'Shifting: Fourth Finger Helps the Move to Third Position', 'the player uses fourth finger as part of a position change into third position', 'The clue says the fourth finger helps get from G up to third position for the next note. Use the finger as a guide for the shift rather than treating it as an isolated note.', 'the shift lacks a guide into the new position', 'placing fourth finger without using it to organize the next position', 'Practice the fourth-finger note and the following third-position landing as one connected move.', 'Did the fourth finger help guide the shift?', ARRAY['shifting','fourth-finger']::text[]),
      ('3bAWqnjPfV4', 583, 638, 'Shifting: Quick Half-Position Visit', 'the player needs a brief half-position move and immediate return', 'The clue says to quickly go into half position for one B natural, then come right back out. Keep the shift small, temporary, and rhythmically clean.', 'a brief half-position note disrupts the phrase', 'staying mentally in the shifted position too long', 'Practice the B-natural shift as touch-and-return, then add the crescendo group.', 'Did the half-position visit return cleanly to the phrase?', ARRAY['shifting','intonation','performance-context']::text[]),
      ('517uzXPQ3xg', 249, 274, 'Bow Change and Slide: Start Moving Before the Change', 'the player wants a small slur or slide to speak smoothly through a bow change', 'The clue says to begin sliding the finger before the bow stops moving and before the bow change. Coordinate left-hand travel with the bow change so the gesture feels easy.', 'the slide or slur bumps because the finger waits until after the bow change', 'separating the left-hand slide from the bow motion', 'Start the finger slide just before the bow change, then repeat slowly until it feels continuous.', 'Did the slide and bow change feel connected?', ARRAY['bow-changes','shifting']::text[]),
      ('517uzXPQ3xg', 617, 675, 'Vibrato, Bow Speed, and Growth', 'the player is shaping a growing sound with bow speed, pressure, and vibrato', 'The clue says growth can come from faster bow, more pressure, added vibrato, or a combination. Choose the mixture deliberately instead of simply getting louder.', 'a crescendo or growth gesture lacks a clear sound strategy', 'adding volume without deciding between bow speed, pressure, and vibrato', 'Play the growth three ways: bow speed only, vibrato only, then combined.', 'Which ingredient made the sound grow best?', ARRAY['vibrato','bow-speed','arm-weight']::text[]),
      ('517uzXPQ3xg', 666, 722, 'Performance Context: Making the Note Pop', 'the learner wants a note or color change to pop out musically', 'The clue says the player jumps to the A string because he wants the note to pop, then backs off. Frame the passage as musical color and emphasis rather than a generic shift.', 'the excerpt is framed as shifting even though the clue is about color and emphasis', 'making a string choice mechanically without shaping the pop and release', 'Play the note once plainly, then once with the intended pop and immediate backing off.', 'Did the color change speak without overdoing it?', ARRAY['performance-context','string-crossing','bow-speed']::text[]),
      ('517uzXPQ3xg', 811, 861, 'Vibrato: Use It for Boldness, Then Back Off', 'the player is choosing register and vibrato size for a bold sound', 'The clue says to use vibrato to make the sound bolder, then back off on the pickup. Shape vibrato size as part of the phrase, not as a constant setting.', 'vibrato stays the same size when the phrase needs contrast', 'using big vibrato everywhere instead of backing off after the bold moment', 'Play the bold note with larger vibrato, then deliberately reduce vibrato on the pickup.', 'Did the vibrato shape the phrase instead of flattening it?', ARRAY['vibrato','performance-context']::text[]),
      ('69_-GJO5Z9M', 49, 91, 'Shifting: Arm Motion and Pitch Check', 'the player uses the arm to pull the hand forward and taps to verify pitch', 'The clue says the arm pulls the hand forward and that tapping can check whether the pitch is right. Coordinate the larger motion first, then verify intonation.', 'the player tries to shift with fingers alone and loses pitch certainty', 'moving the fingers without the arm and skipping the pitch check', 'Use the arm to move, then tap the target note before committing to the shift.', 'Did the arm motion and tap confirm the pitch?', ARRAY['shifting','intonation']::text[]),
      ('69_-GJO5Z9M', 101, 151, 'Shifting: Fourth Finger Lands After the Position Change', 'the player shifts to fourth position and drops fourth finger for a clean arrival', 'The clue describes shifting to fourth position, then popping fourth finger down for a clean shift. Treat the fourth finger as the arrival after the larger hand move.', 'the fourth finger is asked to reach before the hand has arrived', 'stretching the finger instead of shifting the hand frame first', 'Shift the hand to fourth position, pause, then drop fourth finger cleanly.', 'Did the fourth finger land easily after the shift?', ARRAY['shifting','fourth-finger']::text[])
  ) AS f(
    youtube_video_id,start_seconds,end_seconds,segment_title,use_when,teaching_summary,
    problem_statement,common_failure_mode,suggested_experiment,reflection_prompt,tag_slugs
  )
),
updated AS (
  UPDATE public.segments s
  SET
    segment_title = f.segment_title,
    use_when = f.use_when,
    teaching_summary = f.teaching_summary,
    problem_statement = f.problem_statement,
    common_failure_mode = f.common_failure_mode,
    suggested_experiment = f.suggested_experiment,
    reflection_prompt = f.reflection_prompt,
    notes = trim(coalesce(s.notes, '') || ' Semantic drift cleanup batch 1: title, summary, and tags aligned to contextual_clues.')
  FROM fixes f
  JOIN public.videos v ON v.youtube_video_id = f.youtube_video_id
  WHERE s.video_id = v.id
    AND s.start_seconds = f.start_seconds
    AND s.end_seconds = f.end_seconds
    AND s.review_status = 'ai_proposed'
    AND s.is_public = false
  RETURNING s.id, f.tag_slugs
),
deleted_tags AS (
  DELETE FROM public.segment_tags st
  USING updated u
  WHERE st.segment_id = u.id
),
inserted_tags AS (
  INSERT INTO public.segment_tags (segment_id, tag_id, relevance, is_primary, assigned_by)
  SELECT
    u.id,
    t.id,
    CASE tag_slug.ordinality WHEN 1 THEN 95 WHEN 2 THEN 90 ELSE 85 END,
    tag_slug.ordinality = 1,
    'semantic_drift_cleanup'
  FROM updated u
  CROSS JOIN LATERAL unnest(u.tag_slugs) WITH ORDINALITY AS tag_slug(slug, ordinality)
  JOIN public.tags t ON t.slug = tag_slug.slug
  ON CONFLICT (segment_id, tag_id) DO UPDATE SET
    relevance = EXCLUDED.relevance,
    is_primary = EXCLUDED.is_primary,
    assigned_by = EXCLUDED.assigned_by
  RETURNING segment_id
)
SELECT
  (SELECT count(*) FROM updated) AS updated_segments,
  (SELECT count(*) FROM inserted_tags) AS inserted_segment_tags;

COMMIT;
