-- 018_semantic_drift_cleanup_batch_2.sql
-- Conservative semantic cleanup for high-confidence ai_proposed drift rows.
-- Keeps rows unpublished; improves title/use/summary/tags from direct transcript clues.

BEGIN;

WITH fixes AS (
  SELECT *
  FROM (
    VALUES
      ('1R8WiILKtJs', 65, 114, 'Double Stops in Thirds: Intonation Setup', 'the player is working on thirds that are hard to tune reliably', 'The clue says thirds are difficult to get in tune. Treat the passage as double-stop intonation work: set the hand frame slowly, then check whether both notes settle together.', 'thirds do not lock in tune as a stable shape', 'moving both fingers at once without a reliable frame', 'Tune the lower note, add the upper note silently, then play both as a settled double stop.', 'Did both notes settle into tune together?', ARRAY['double-stops','intonation']::text[]),
      ('3bAWqnjPfV4', 110, 167, 'Shifting Down on the Open-String Window', 'the player needs a clean downward shift around measure seven without exposing the motion', 'The clue names shifting down during the last four sixteenths of measure seven. Use the open-string or fast-note window to organize the move so the shift does not sound late or exposed.', 'the downward shift interrupts the measure instead of fitting inside it', 'waiting too long and forcing the hand to jump', 'Practice only the last four sixteenths, timing the hand move before the target note.', 'Did the shift happen inside the musical window?', ARRAY['shifting','performance-context']::text[]),
      ('3bAWqnjPfV4', 723, 780, 'Measure 43: Shift Back to First Position', 'the player needs the measure-forty-three return to first position to feel mapped and repeatable', 'The clue repeats shift, shift, shift while naming measure 43 and first position. Mark the return to first position as a specific planned event, then practice the surrounding notes as anchors.', 'the return to first position is vague and unreliable', 'thinking of the passage as many shifts instead of one mapped return', 'Name the note that confirms first position, then practice two notes before and after it.', 'Where exactly did first position become secure again?', ARRAY['shifting','intonation']::text[]),
      ('517uzXPQ3xg', 28, 77, 'Third Position: Vibrato Color on the D String', 'the player is choosing third position for color and vibrato on the D string', 'The clue names third position, vibrato, and the D and G strings. Frame the passage as a position and color choice: third position gives the hand room to vibrate and shape the sound.', 'the position choice is treated as generic shifting rather than sound color', 'moving position without deciding what tone or vibrato it should create', 'Play the note in first and third position, then choose the version with the better vibrato color.', 'Did third position improve the color or only change the fingering?', ARRAY['shifting','vibrato','performance-context']::text[]),
      ('517uzXPQ3xg', 106, 159, 'First-to-Third Position: Finding the G', 'the player is finding a G by moving cleanly from first to third position', 'The clue says first position, third position, and G. Use the G as the landing target and make the shift small enough that pitch stays organized.', 'the target G is not reliably found after the position change', 'shifting by distance without hearing the landing pitch first', 'Sing or name the G, shift silently, then play to confirm the target.', 'Did the hand arrive where the G was already expected?', ARRAY['shifting','intonation']::text[]),
      ('517uzXPQ3xg', 540, 578, 'Fast Notes: Choosing the Quieter Position', 'the player is choosing a position so fast notes do not pop out too much', 'The clue says the fast notes are harder and that the player does not want one note to pop too much. Pick the position and string route that keeps the passage clean without over-accenting the note.', 'a fast note draws too much attention because the position choice is too exposed', 'choosing the easiest fingering without checking the musical effect', 'Try the position choice at tempo and listen only for whether any note pops out.', 'Did the position make the fast notes cleaner and less exposed?', ARRAY['shifting','performance-context']::text[]),
      ('69_-GJO5Z9M', 143, 180, 'Hand Frame: First to Third Position Octave', 'the player is using an octave frame to organize first-to-third-position travel', 'The clue names first position, third position, hand frame, and octave. Use the octave shape as a physical checkpoint so the shift lands with a stable left-hand frame.', 'the hand frame changes shape during the shift', 'aiming for a single note while losing the octave relationship', 'Set the octave frame, shift, then check whether the same shape is still present.', 'Did the octave frame survive the position change?', ARRAY['shifting','intonation']::text[]),
      ('69_-GJO5Z9M', 192, 227, 'Landing the Shift: Fourth Finger Check', 'the player uses fourth finger to confirm that the shifted hand has landed correctly', 'The clue connects correct landing, fourth finger, and the return down using the arm and hand. Treat fourth finger as a landing check after the shift rather than a reach.', 'the fourth finger is unreliable because the hand has not landed first', 'stretching the pinky instead of moving the arm and hand together', 'Shift the arm and hand first, then place fourth finger without reaching.', 'Did fourth finger feel like a drop rather than a stretch?', ARRAY['shifting','fourth-finger']::text[]),
      ('69_-GJO5Z9M', 230, 255, 'Arm-Led Shift and Extension Setup', 'the player is coordinating arm motion, hand slide, and extension during a shift', 'The clue says to use the arm, let the hand slide, and then deal with extensions. Make the large motion first so the later extension is small and organized.', 'the extension is asked to solve a shift the arm has not completed', 'reaching with fingers while the hand stays behind', 'Move with the arm first, pause in the new frame, then add the extension.', 'Did the extension become smaller after the arm moved?', ARRAY['shifting','intonation']::text[]),
      ('69_-GJO5Z9M', 290, 313, 'Hand Frame: Land in the Correct Spot', 'the player is checking whether the hand arrives in the correct position before building the octave', 'The clue names hand position, the correct spot, and forming an octave. Make the landing specific, then use the octave as the test of whether the frame is right.', 'the octave exposes that the hand landed in the wrong place', 'forming the octave before confirming the basic hand position', 'Land the hand, check the base note, then form the octave without moving the wrist.', 'Did the octave confirm the landing spot?', ARRAY['shifting','intonation']::text[]),
      ('69_-GJO5Z9M', 317, 360, 'Descending Shift: Arm and Hand Combination', 'the player needs the downward shift to reverse the same arm-and-hand motion used ascending', 'The clue says coming down is similar but backwards, using arm and hand. Practice the descent as the reverse path rather than a separate guess.', 'the descending shift does not retrace the organized upward motion', 'dropping the hand independently of the arm', 'Play the ascent, freeze the frame, then reverse the same arm-and-hand path downward.', 'Did the descent feel like the same motion in reverse?', ARRAY['shifting','intonation']::text[]),
      ('69_-GJO5Z9M', 429, 484, 'Third Position: Arm Memory for the Shift', 'the player is using arm motion to make third position repeatable', 'The clue says the arm already knows how to shift into third position. Rely on that larger physical memory, then check the pitch after the arrival.', 'the player overthinks the note target and interrupts the shift', 'using finger aim instead of the arm motion that already works', 'Repeat the arm-led shift to third position three times before adding the passage.', 'Could the arm find third position consistently?', ARRAY['shifting','intonation']::text[]),
      ('69_-GJO5Z9M', 667, 720, 'Position Awareness: Keep Fingers Close', 'the player needs fingers to stay close and organized in position', 'The clue says the fingers are too tall and too far over, and asks for more articulated position awareness. Keep the fingers near the string so the hand frame remains available.', 'fingers lift too high and lose their relationship to the position', 'resetting each finger from far above the string', 'Hover the fingers close to the string, then play the passage with minimal lift.', 'Did the fingers stay close enough to preserve the position?', ARRAY['shifting','practice-strategy']::text[]),
      ('69_-GJO5Z9M', 1045, 1090, 'Fingering Map: Popping Fourth Finger', 'the player is following a specific fingering map that requires a quick fourth-finger placement', 'The clue lists the fingering and says to pop the fourth finger. Use the written map to plan where fourth finger drops, then keep the rest of the hand quiet.', 'the fingering map falls apart at the fourth-finger placement', 'reacting to fourth finger late instead of preparing its place in the pattern', 'Say the fingering aloud while placing each finger silently, then add the bow.', 'Was fourth finger ready before it had to sound?', ARRAY['fourth-finger','shifting']::text[]),
      ('69_-GJO5Z9M', 1124, 1168, 'Fifth to Third Position: Hand Frame and Extension', 'the player is moving from fifth to third position while keeping extension choices organized', 'The clue names fifth position, back to third, and extension. Keep the hand frame stable through the position change so the extension does not distort the landing.', 'the extension pulls the hand out of frame during the fifth-to-third move', 'reaching first and trying to shift afterward', 'Practice fifth to third without the extension, then add the extension only after the frame is secure.', 'Did the hand frame stay stable when the extension appeared?', ARRAY['shifting','intonation']::text[]),
      ('7YvI9La1T2U', 133, 180, 'Mini Shift: Finding E-flat for Fourth Finger', 'the player is using a small shift to make fourth finger find E-flat cleanly', 'The clue names E-flat, fourth finger, and a mini shift with second finger. Move the hand just enough that fourth finger can land naturally instead of stretching for the pitch.', 'fourth finger reaches for E-flat from the wrong hand position', 'treating the E-flat as a pinky stretch instead of a mini shift', 'Let second finger guide the mini shift, then drop fourth finger onto E-flat.', 'Did E-flat feel close after the mini shift?', ARRAY['shifting','fourth-finger','intonation']::text[]),
      ('7YvI9La1T2U', 207, 225, 'Fourths and Inverted Chords: Intonation Trick', 'the player is using a shifting trick to tune a fourth or inverted chord shape', 'The clue says another fourth and that the shifting trick makes it easier to play in tune. Treat the shift as an intonation setup for the chord shape.', 'the interval is out of tune because the hand shape is not prepared', 'trying to correct the chord after landing instead of setting it up with the shift', 'Practice the shift into the chord shape silently, then play only after the frame feels placed.', 'Did the shift make the interval easier to tune?', ARRAY['intonation','shifting','double-stops']::text[]),
      ('7YvI9La1T2U', 258, 291, 'Reverse Chord: First-Finger Shift Guide', 'the player is using first finger to guide a shift in a reverse chord passage', 'The clue names a reverse chord, important top and bottom notes, and a similar shift with first finger. Let first finger guide the position so the outer notes stay meaningful.', 'the chord shape loses its anchor notes during the shift', 'focusing on the middle of the pattern instead of the top and bottom anchors', 'Shift with first finger, then check the top and bottom notes before filling in the chord.', 'Did first finger preserve the important outer notes?', ARRAY['shifting','intonation','double-stops']::text[]),
      ('7YvI9La1T2U', 360, 408, 'Shift Guide: First Finger and D-String Color', 'the player is using first finger to guide a shift while controlling extra D-string sound', 'The clue describes a shifting technique using first finger and minimizing sound on the D string. Coordinate the guide finger with a cleaner string color.', 'the shift guide creates unwanted D-string sound', 'letting the guide finger or bow make the shift too audible', 'Practice the first-finger guide silently, then add the bow with the D string kept quiet.', 'Could the shift guide work without extra D-string noise?', ARRAY['shifting','string-crossing']::text[]),
      ('7YvI9La1T2U', 391, 439, 'Shift Timing: Give the Finger Time to Land', 'the player needs to give the shifting finger enough time to arrive accurately', 'The clue says the same shifting technique gives the finger a chance to land in the right spot. Build time into the motion so intonation is prepared before the note speaks.', 'the finger arrives late and the pitch is corrected after the fact', 'playing the target note before the hand has finished traveling', 'Slow the rhythm enough that the guide finger lands before the bow speaks.', 'Did the finger land before the sound started?', ARRAY['shifting','intonation']::text[]),
      ('9evdTcBy5Hc', 27, 66, 'Fourth Finger Setup: A-flat Shape', 'the player is setting up a fourth-finger A-flat shape without losing hand organization', 'The clue mentions fourth finger and A-flat. Prepare the hand shape for the lowered pitch so the pinky placement is accurate and not tense.', 'A-flat is missed because fourth finger is placed from an unprepared frame', 'reaching the pinky back without organizing the lower fingers', 'Place the lower fingers first, then drop fourth finger to A-flat without squeezing.', 'Did A-flat arrive from the hand shape rather than a reach?', ARRAY['fourth-finger','intonation']::text[]),
      ('9evdTcBy5Hc', 134, 162, 'Beginner Fingering: Avoiding the Shift', 'the player is choosing a beginner-friendly fingering that avoids an unnecessary shift', 'The clue says the fingerings are for beginners and that the shift is being avoided. Treat the segment as practical fingering choice, not as a shifting exercise.', 'the passage is made harder by adding a shift the player does not need yet', 'choosing an advanced route before the stable beginner fingering works', 'Play the beginner fingering slowly and notice whether avoiding the shift improves reliability.', 'Did the no-shift option make the passage easier to control?', ARRAY['practice-strategy','shifting']::text[]),
      ('9evdTcBy5Hc', 242, 271, 'Fourth Finger Substitute: Moving Down to First Finger', 'the player is replacing or supporting fourth finger by moving down to first finger', 'The clue says fourth finger and then going down to first finger. Use the move as a fingering substitution: decide whether fourth finger or first finger gives the cleaner result.', 'the fingering switch is unclear and the hand reacts late', 'changing fingers without planning the hand move between them', 'Practice fourth finger to first finger as a two-note move before restoring rhythm.', 'Which finger choice gave the cleaner pitch and sound?', ARRAY['fourth-finger','shifting','intonation']::text[]),
      ('CvWVNMybMeQ', 76, 107, 'Hand Position: Natural Octave Frame', 'the player is checking whether the hand position naturally forms an octave', 'The clue says the hand position allows the player to play an octave naturally. Use the octave as a frame test: the hand should feel organized before the notes are played.', 'the octave feels stretched because the hand frame is not set', 'trying to build the octave note by note instead of placing the frame', 'Set the hand frame silently, then play the octave without changing the wrist.', 'Did the octave feel natural from the hand position?', ARRAY['shifting','intonation']::text[])
  ) AS f(
    youtube_video_id,start_seconds,end_seconds,segment_title,use_when,teaching_summary,
    problem_statement,common_failure_mode,suggested_experiment,reflection_prompt,tag_slugs
  )
),
updated AS (
  UPDATE public.segments s
  SET
    segment_title = f.segment_title,
    use_when = f.use_when,
    teaching_summary = f.teaching_summary,
    problem_statement = f.problem_statement,
    common_failure_mode = f.common_failure_mode,
    suggested_experiment = f.suggested_experiment,
    reflection_prompt = f.reflection_prompt,
    notes = trim(coalesce(s.notes, '') || ' Semantic drift cleanup batch 2: title, summary, and tags aligned to contextual_clues.')
  FROM fixes f
  JOIN public.videos v ON v.youtube_video_id = f.youtube_video_id
  WHERE s.video_id = v.id
    AND s.start_seconds = f.start_seconds
    AND s.end_seconds = f.end_seconds
    AND s.review_status = 'ai_proposed'
    AND s.is_public = false
  RETURNING s.id, f.tag_slugs
),
deleted_tags AS (
  DELETE FROM public.segment_tags st
  USING updated u
  WHERE st.segment_id = u.id
),
inserted_tags AS (
  INSERT INTO public.segment_tags (segment_id, tag_id, relevance, is_primary, assigned_by)
  SELECT
    u.id,
    t.id,
    CASE tag_slug.ordinality WHEN 1 THEN 95 WHEN 2 THEN 90 ELSE 85 END,
    tag_slug.ordinality = 1,
    'semantic_drift_cleanup'
  FROM updated u
  CROSS JOIN LATERAL unnest(u.tag_slugs) WITH ORDINALITY AS tag_slug(slug, ordinality)
  JOIN public.tags t ON t.slug = tag_slug.slug
  ON CONFLICT (segment_id, tag_id) DO UPDATE SET
    relevance = EXCLUDED.relevance,
    is_primary = EXCLUDED.is_primary,
    assigned_by = EXCLUDED.assigned_by
  RETURNING segment_id
)
SELECT
  (SELECT count(*) FROM updated) AS updated_segments,
  (SELECT count(*) FROM inserted_tags) AS inserted_segment_tags;

COMMIT;
