/* Static/local-only MVP. No API calls, storage, cookies, analytics, or AI. */
const ROUTES=[
{id:'returning-restart-short',entry:'returning',need:'restart',time:'short',title:'Rebuilding Contact After Time Away',videoId:'REPLACE_WITH_YOUTUBE_VIDEO_ID',start:252,watchIf:'You are returning after time away and want a small, non-punishing place to begin.',why:'A short reset is often more useful than trying to recover everything at once.',notice:'Watch for what returns before deciding what needs fixing.',tryThis:'Play one open string slowly. Reset contact before adding speed or repertoire.',tags:['returning','restart','5–10 minutes'],notFor:'Not for sharp pain, injury-related concerns, or a situation that needs a teacher who can see you.'},
{id:'starting-practice-short',entry:'starting',need:'practice',time:'short',title:'A Realistic First Step',videoId:'REPLACE_WITH_YOUTUBE_VIDEO_ID',start:0,watchIf:'You are new and want a grounded first page rather than a giant checklist.',why:'Starting small protects curiosity and gives you something real to notice.',notice:'Notice what you can understand before worrying about doing it perfectly.',tryThis:'Choose one question to carry into your first lesson or first practice session.',tags:['starting fresh','practice','5–10 minutes'],notFor:'A teacher can help with instrument setup and early physical habits.'},
{id:'stuck-problem-medium',entry:'stuck',need:'problem',time:'medium',title:'Stop Trying to Fix the Whole Problem',videoId:'REPLACE_WITH_YOUTUBE_VIDEO_ID',start:0,watchIf:'You have a real problem but cannot yet tell which part matters most.',why:'Separating observation from correction can keep one issue from becoming five imagined ones.',notice:'Watch for the smallest observable change before assigning a cause.',tryThis:'Name one thing you can hear or feel without trying to correct it yet.',tags:['stuck','problem','15–30 minutes'],notFor:'Use a teacher or qualified clinician for injury, persistent pain, or safety concerns.'},
{id:'stuck-reading-medium',entry:'stuck',need:'reading',time:'medium',title:'Reading New Music Without Chasing Every Note',videoId:'REPLACE_WITH_YOUTUBE_VIDEO_ID',start:0,watchIf:'Reading unfamiliar music feels like a flood of details.',why:'Reading becomes more workable when you decide what to notice first.',notice:'Watch how the eye and body are given fewer jobs at one time.',tryThis:'Read one short line while prioritizing only pulse and direction.',tags:['reading','stuck','15–30 minutes'],notFor:'This is one route into reading, not a full sight-reading curriculum.'},
{id:'helper-help-any',entry:'helper',need:'help',time:'any',title:'Helping Without Taking Over',videoId:'REPLACE_WITH_YOUTUBE_VIDEO_ID',start:0,watchIf:'You are supporting a player without becoming their teacher or practice police.',why:'A useful helper protects agency before offering solutions.',notice:'Watch for the difference between noticing and correcting.',tryThis:'Ask one open question before offering a suggestion.',tags:['parent','teacher','helper'],notFor:'This does not replace a player’s teacher or address family conflict.'},
{id:'exploring-understand-long',entry:'exploring',need:'understand',time:'long',title:'Choose a Thread and Follow It',videoId:'REPLACE_WITH_YOUTUBE_VIDEO_ID',start:0,watchIf:'You want to explore Ben’s teaching without needing a problem solved first.',why:'The archive is more useful when you enter through a live question rather than trying to consume it all.',notice:'Notice which idea keeps pulling your attention.',tryThis:'Choose one related resource to open next, then stop.',tags:['exploring','more time'],notFor:'Choose another route if you need a concrete next action.'}
];
const S={entry:null,level:null,need:null,time:null};const app=document.querySelector('#app');
const E=[['starting','Starting fresh'],['returning','Returning after time away'],['stuck','Stuck on something'],['helper','Helping someone else'],['exploring','Exploring Ben’s materials']];
const L=[['never','Never played'],['beginner','Beginner'],['returning-player','Returning player'],['active','Active player'],['helper-level','Teacher / parent / helper']];
const N=[['practice','Know what to practice'],['restart','Restart well'],['problem','Solve a problem'],['reading','Read better'],['understand','Understand a piece / technique'],['help','Help someone else']];
const T=[['short','5–10 minutes'],['medium','15–30 minutes'],['long','Longer'],['any','It varies']];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function render(x){app.innerHTML=x;app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(b.dataset.choice));app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));app.querySelector('h1,h2')?.focus?.()}function list(x){return `<div class="choices">${x.map(([a,b])=>`<button class="choice" data-choice="${a}">${b}</button>`).join('')}</div>`}function bars(n){return `<p class="step">${[1,2,3,4].map(i=>`<i class="bar ${i<=n?'on':''}"></i>`).join('')} Step ${n} of 4</p>`}
function home(){render(`<article class="card"><p class="eyebrow">Stand Partner · Free First Turn</p><h1 tabindex="-1">Not sure where to begin?</h1><p class="lede">Answer a few quick questions. Get one specific page from Ben’s teaching.</p><p class="pill">🔒 No account · No memory · No data sent</p><div class="buttons"><button class="btn" data-action="start">Turn to a page</button><button class="btn secondary" data-action="browse">Browse a sample route</button></div><p class="helper">The same choices lead to the same route. Your choices disappear when you leave.</p></article>`)}
function onb(n){let title,items;if(n===1){title='Why are you here?';items=E}else if(n===2){title='Where are you now?';items=L}else if(n===3){title='What would help most right now?';items=N}else{title='How much room do you have today?';items=T}render(`<article class="card">${bars(n)}<p class="eyebrow">Optional quick orientation</p><h2 tabindex="-1">${title}</h2>${list(items)}${n===4?'<p class="notice">This changes only the size of the first suggestion. Nothing is saved.</p>':''}</article>`)}
function scope(){render(`<article class="card"><p class="eyebrow">Before your first route</p><h2 tabindex="-1">What this guide does—and does not do</h2><p class="lede">It turns you toward a useful page from Ben Chan Violin’s teaching. It does not diagnose your playing, replace a teacher, or tell you there is one correct answer.</p><div class="buttons"><button class="btn" data-action="build">Build my starting page</button><button class="btn secondary" data-action="home">Back</button></div></article>`)}
function pick(){return ROUTES.find(r=>r.entry===S.entry&&r.need===S.need&&(r.time===S.time||r.time==='any'))||ROUTES.find(r=>r.entry===S.entry&&r.need===S.need)||ROUTES.find(r=>r.need===S.need)||ROUTES.find(r=>r.entry===S.entry)||ROUTES[0]}
function route(start){let r=pick();render(`<article class="card"><p class="eyebrow">${start?'Built from your answers':'A new turn'}</p><h2 tabindex="-1">${start?'Here’s your starting page':'Your next page'}</h2><div class="tags">${r.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><h3>${esc(r.title)}</h3><p class="helper">${esc(r.watchIf)}</p><div class="panel"><b>Why this page</b><br>${esc(r.why)}</div><div class="panel"><b>Try this first</b><br>${esc(r.tryThis)}</div><div class="buttons"><button class="btn" data-action="resource">Open page</button><button class="btn secondary" data-action="ask">Ask for another route</button></div></article>`)}
function ask(){render(`<article class="card"><p class="eyebrow">Turn again</p><h2 tabindex="-1">What is going on?</h2><p class="helper">For this free version, choose a route. The Studio app can handle messier context and ongoing notes.</p>${list(N)}<div class="buttons"><button class="btn subtle" data-action="home">Return home</button></div></article>`)}
function resource(){let r=pick(),src=r.videoId.startsWith('REPLACE_')?'':`https://www.youtube-nocookie.com/embed/${encodeURIComponent(r.videoId)}?start=${Number(r.start||0)}&rel=0`;render(`<article class="card"><p class="eyebrow">Your page</p><h2 tabindex="-1">${esc(r.title)}</h2>${src?`<div class="video"><iframe title="${esc(r.title)}" src="${src}" allowfullscreen></iframe></div>`:`<p class="notice"><b>Video placeholder.</b><br>Replace <code>videoId</code> in <code>app.js</code> with a YouTube video ID.</p>`}<div class="panel"><b>What to notice</b><br>${esc(r.notice)}</div><div class="panel"><b>Try this</b><br>${esc(r.tryThis)}</div><p class="helper"><b>Boundary:</b> ${esc(r.notFor)}</p><div class="buttons"><button class="btn" data-action="helped">This helped</button><button class="btn secondary" data-action="not">Not my issue</button><button class="btn subtle" data-action="ask">Turn again</button></div></article>`)}
function check(){render(`<article class="card"><p class="eyebrow">Quick check-in</p><h2 tabindex="-1">Did this give you a useful next step?</h2>${list([['yes','Yes, this helped'],['somewhat','Somewhat'],['no','No — turn again']])}<div class="buttons"><button class="btn subtle" data-action="studio">What does Stand Partner add?</button></div></article>`)}
function nope(){render(`<article class="card"><p class="eyebrow">That is useful information</p><h2 tabindex="-1">This may not be the right page.</h2><p class="lede">A wrong turn is not a failed session.</p><div class="buttons"><button class="btn" data-action="ask">Tell me more</button><button class="btn secondary" data-action="home">Return home</button></div></article>`)}
function studio(){render(`<article class="card"><p class="eyebrow">Stand Partner on Studio</p><h2 tabindex="-1">One page can be enough. Your playing is longer than one page.</h2><p class="lede">The Studio app is for ongoing routes, saved pages, personal notes, and a working playbook built from what helps you.</p><div class="panel"><b>This free guide</b><br>One local, private route. Nothing remembered.</div><div class="panel"><b>Stand Partner on Studio</b><br>Continued routing, saved pages, and room to build a personal playbook.</div><div class="buttons"><a class="btn" href="REPLACE_WITH_STUDIO_APP_URL" target="_blank" rel="noopener">Open Stand Partner</a><button class="btn secondary" data-action="home">Return home</button></div></article>`)}
function choose(v){let h=app.querySelector('h2')?.textContent||'';if(h.includes('Why are')){S.entry=v;onb(2)}else if(h.includes('Where are')){S.level=v;onb(3)}else if(h.includes('What would help')){S.need=v;onb(4)}else if(h.includes('How much room')){S.time=v;scope()}else if(h.includes('What is going')){S.need=v;S.time=S.time||'any';route(false)}else if(h.includes('Did this')){v==='yes'?studio():ask()}}function action(v){if(v==='start')onb(1);if(v==='browse'){Object.assign(S,{entry:'returning',need:'restart',time:'short'});route(true)}if(v==='home'){Object.assign(S,{entry:null,level:null,need:null,time:null});home()}if(v==='build')route(true);if(v==='resource')resource();if(v==='ask')ask();if(v==='helped')check();if(v==='not')nope();if(v==='studio')studio()}
document.querySelector('#how').onclick=()=>document.querySelector('#modal').showModal();document.querySelector('#close').onclick=()=>document.querySelector('#modal').close();home();
